### ISSUE TITLE
I have problem in proxy in deployment 

### ISSUE THREAD

**Issue by Ehab97** [vitejs/vite-plugin-react#100]
### Describe the bug

I have problem in proxy to cookies session in deployment  it's working fine in localhost on my machine 

when i try to login with google3 it's working only on local not on host server

that's my vite.confgi.ts file code
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/

interface DefaultConfig {
  plugins: any[];
  server: {
    proxy: {
      '/api': {
        target: string;
        changeOrigin: boolean;
        configure: (proxy: any, options: any) => void;
        secure: boolean;
      }
    }
  }
}

const defaultConfig = {
  plugins: [
    react({ include: "**/*.tsx", }),
  ],
  server: {
    proxy: {
      '/api': {
        target: 'https://tame-lime-rooster-tie.cyclic.app',
        changeOrigin: true,
        configure: (proxy, options) => {
          proxy.on('proxyReq', (proxyReq, req, res) => {
            if (!req.headers.cookie) {
              return;
            }
            console.log('req.headers.cookie', req.headers.cookie)
            proxyReq.setHeader('cookie', req.headers.cookie);
          });
        },
        secure: false
      }
    }
  }
}

export default defineConfig(({ command, mode }) => {
  if (command === 'serve') {
    const isDev = mode === 'development';
    return {
      ...defaultConfig,
      server: {
        proxy: {
          '/api': {
            target: isDev ? 'http://localhost:5000' : 'https://tame-lime-rooster-tie.cyclic.app',
            changeOrigin: true,
            configure: (proxy, options) => {
              proxy.on('proxyReq', (proxyReq, req, res) => {
                if (!req.headers.cookie) {
                  return;
                }
                console.log('req.headers.cookie', req.headers.cookie)
                proxyReq.setHeader('cookie', req.headers.cookie);
              });
            },
            secure: false
          }
        }
      }
    }
  } else {
    return defaultConfig;
  }
});
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cn8lwk?file=package.json

### Steps to reproduce

npm run dev

### System Info

```shell
System:
    OS: macOS 11.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 775.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Chrome Canary: 112.0.5568.0
    Firefox: 109.0
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I don't understand, have you problem with running Vite development proxy on a distant machine?

**Comment by Ehab97** [comment]
> I don't understand, have you problem with running Vite development proxy on a distant machine?

i have a problem with proxy on host deployment but not on the local server for example when i'm in devepolemnt mode 'http://localhost:5000' working fine but in production mode 'https://tame-lime-rooster-tie.cyclic.app' not working

**Comment by ArnaudBarre** [comment]
How are you deploying your app?
Vite proxy is a dev feature? You shouldn't run `vite dev` in production

**Comment by Ehab97** [comment]
> How are you deploying your app? Vite proxy is a dev feature? You shouldn't run `vite dev` in production

on vercel  also there's a Reproduction here
https://stackblitz.com/edit/vitejs-vite-cn8lwk

**Comment by ArnaudBarre** [comment]
Vite proxy is a development feature. It's used for `vite preview` too to test your build app locally, but Vite is not running (and shouldn't) run in prod.

**Comment by Ehab97** [comment]
> Vite proxy is a development feature. It's used for `vite preview` too to test your build app locally, but Vite is not running (and shouldn't) run in prod.

OK so I can not use proxy in production, 
And what the replacement for it ,
Or is this feature will be added in the future thanks

**Comment by ArnaudBarre** [comment]
The goal of the proxy is to solve the fact that in dev, your app is not served at the same address than your backend.

Your API calls should be written for production, and if doing means your calling `/api`, then in development, you can use the proxy to redirect this from localhost:5000 to to dev backend (for ex. `localhost:8080`)
