### ISSUE TITLE
HMR not working with backend integration 

### ISSUE THREAD

**Issue by jvanmaaren** [vitejs/vite-plugin-react#101]
### Describe the bug

Hi all, I have a problem I hope you can help me with

During development any changes to Javascript doesn't update the DOM, although the server and console both report "[vite] hot updated: /App.tsx"

### Reproduction

https://github.com/jvanmaaren/vite-update-problem

### Steps to reproduce

**Setup**
I'm using a backend integration:
https://vitejs.dev/guide/backend-integration.html#backend-integration

Python is running on port 8000 and is including the dev environment
Vite is running on port 8080

**To reproduce:**

- Install packages: `yarn`
- View `some-other-server/index.html` on port 8000, for instance using: `cd some-other-server && python3 -m http.server 8000`
- Run the dev server: `yarn dev`
- View `localhost:8000`
- Now change the text in App.tsx

### System Info

```shell

  System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 989.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Chrome Canary: 112.0.5574.0
    Edge: 109.0.1518.70
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-react: 3.1.0 => 3.1.0
    vite: 4.1.1 => 4.1.1

```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
This `App` should be `app` because the file name is `app.tsx`.
https://github.com/jvanmaaren/vite-update-problem/blob/ea1888502b58df61513d0bff8d5eb38ccbc57704/src/index.tsx#L2

https://vitejs.dev/guide/troubleshooting.html#vite-detects-a-file-change-but-the-hmr-is-not-working

**Comment by jvanmaaren** [comment]
@sapphi-red thanks for your response. Somehow the filename was showing as capitalized on my file system.

To remove confusion, I've renamed the file to `someapp.tsx`

However the problem persists, can you re-open this issue?

**Comment by ArnaudBarre** [comment]
I think to Follow react convention, this file should be rename to App.tsx actually.

@jvanmaaren Can you tell me if you stil experiencing the issue when the file is `App.tsx`

**Comment by jvanmaaren** [comment]
Thanks for thinking along @ArnaudBarre, yes on my localmachine `App.tsx` doesn't work either

Example is updated to use

``` 
@vitejs/plugin-react: 3.1.0 
    vite: 4.1.1  
```

**Comment by ArnaudBarre** [comment]
I will take a look in the coming days (can't today)

**Comment by sapphi-red** [comment]
Ah, I was able to reproduce. It seems this is caused by duplicated `@react-refresh`.
`index.html` is importing `http://localhost:8080/@react-refresh` and the jsx files are importing `http://localhost:8080/dev_static/@react-refresh`.

https://github.com/vitejs/vite/issues/5656 needs to be fixed to avoid these problems. (related: https://github.com/vitejs/vite/issues/9700#issuecomment-1230467795)

**Comment by ArnaudBarre** [comment]
Thanks for investigating!

So I think this cannot be fixed on the plugin side.

I think we should change the main doc (https://vitejs.dev/guide/backend-integration.html#backend-integration) to say to use 
`viteServer.transformIndexHtml(req.url, html)` like here https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#middleware-mode

**Comment by sapphi-red** [comment]
@ArnaudBarre Would it be possible to detect this on the plugin side?

**Comment by ArnaudBarre** [comment]
I though so when we discussed it, but when we resolve/load the id, Vite as already removed the base prefix, so I don't see how to detect a missing base.

And I don't see how to detect if the runtime code was loaded twice because of two connected browser or because of this issue.

**Comment by sapphi-red** [comment]
When we were discussing I didn't have a concrete idea, but now I have one.
I guess we can detect this by changing `__vite_plugin_react_preamble_installed__` to be in the runtime.
```diff
<script type="module">
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
-  window.__vite_plugin_react_preamble_installed__ = true
+  RefreshRuntime.__vite_plugin_react_preamble_installed__ = true
</script>
```

**Comment by ArnaudBarre** [comment]
Oh no let's keep it on the window and use it to detect that two runtimes are instantiate (and throw in that case)

**Comment by jvanmaaren** [comment]
Thanks for looking into this all ❤️ I'll try again once this is released

**Comment by ArnaudBarre** [comment]
This is only a warning for helping other people having the same issue as you. The real fix is adding the path prefix before @react-refresh in `index.html` (as found by @sapphi-red)

**Comment by jvanmaaren** [comment]
Oh now I understand, many thanks, it's working now

I've updated the example repo
