### ISSUE TITLE
Too slow first render with vite-plugin-windicss

### ISSUE THREAD

**Issue by daydarkln** [vitejs/vite-plugin-react#103]
### Describe the bug

When I'm trying to run dev or storybook on my project I waiting a lot of time to first render will finish. After this everything is ok. 
## How it looks like with `vite-plugin-windicss`:

1. run `yarn storybook`
<img width="878" alt="image" src="https://user-images.githubusercontent.com/27866698/216083686-50a4c936-47d8-41f6-a9cb-49739983bc8f.png">

2. wait a lot of time
<img width="982" alt="image" src="https://user-images.githubusercontent.com/27866698/216083857-306d5880-289a-4c16-9c9f-ca4c67c429e1.png">

3. look at the perfomance tab and feel sadness
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/27866698/216085114-a7961b42-15ae-4997-be5d-430d8f27c04e.png">

As you can see, the huge time spent on 'Idle' process.

## Let's remove `vite-plugin-windicss`
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/27866698/216086671-c2b6d2ec-bf30-4868-9c47-2eec2e42a73d.png">

It's a package from the Hell (**10x** difference in time)

How can I use windi and not to feel infinity suffer?

### In causes of security I cannot show you the repo, but I can show my configs and perfomance details
configs: https://gist.github.com/daydarkln/e35c1053c252f7e047046a72c0035671
perfomance: https://www.mediafire.com/file/vrvpq0unmhvcyud/Profile-20230201T184321.json/file

### Reproduction

npm create vite@latest

### Steps to reproduce

1. run `yarn storybook`
2. wait
3. wait
4. wait
...
n. wait

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 385.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 107.0
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.3.2
    vite: 3.0.0 => 3.0.0
```
```


### Used Package Manager

yarn

### Logs

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
If there is a 10x difference with and without, then it's an issue for this plugin.
But given the storybook wrapper not easy to investigate for them either.
If the lib is to slow, you can use other libs like Tailwind, UnoCSS or maybe something more close to windicss but not widely used that I built: https://github.com/ArnaudBarre/downwind
