### ISSUE TITLE
FastRefresh breaks workers code

### ISSUE THREAD

**Issue by val-o** [vitejs/vite-plugin-react#110]
### Describe the bug

If you are using Vite with barrel exports, you might end up with situation when you have a barrel file like this:

file: dashboard/index.ts
ts`
export * from './helpers'
export * from './components'
`

If there is a web worker (or any other worker) which imports helper from dashboard
ts`
import {dashboardHelpers} from './dashboard'
// some non-ui related work
`

Vite will load components anyway (that's how it works now) and there will be ReactRefresh injected code in all of the components codes, which will fail with following error, since there are hard references to window

`Uncaught ReferenceError: window is not defined`

Exptected: 
Plugin should have some checks inside injected code which guards from failing inside non-window contexts

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pv5mkp?file=src/main.tsx

### System Info

```shell
"vite": "^4.0.4",
"@vitejs/plugin-react": "^3.0.1",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This would require having one more set of transformation per component, which is costly for no benefice.
Vite HMR doesn't play nice in HMR even without the worker issue (because any change in one file part of a barrel export is propagated to all the importers of the barrel file, even if few actually uses the initial file).

You should update you code to remove these extra files (or at least use scoped imports for worker code)

**Comment by val-o** [comment]
Thanks @ArnaudBarre , but maybe we can just add additional check inside injected code, so if there is no window just do no-op on hot-update?

**Comment by ArnaudBarre** [comment]
I'm not sure I want to help making it a no-op to import components inside worker. This will probably be tree-shaken out by rollup at build time, but this will increase your build time and putting at risk of importing unwanted side effects. And then you will have to deal with what it means to import CSS in a worker.

Barrels exports sounded cools, I used them a lot few years ago, but this is a pain for tooling for the very small benefice of making imports "nice".
