### ISSUE TITLE
Cannot find module 'react/jsx-runtime' after creating a project

### ISSUE THREAD

**Issue by Mikilll94** [vitejs/vite-plugin-react#114]
### Describe the bug

![Screenshot 2023-03-03 at 09 08 54](https://user-images.githubusercontent.com/17653648/222666220-3b70b8a2-58e0-49ad-b840-ead4389f5ff2.png)

After creating a project using this command `yarn create vite test-admin --template react-ts` I am getting the following errors in `App.tsx`

```
Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)
```

Also `index.tsx` is throwing this error:
```
Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)
```

### Reproduction

I have added repro project below

### Steps to reproduce

Open this project in VSCode and go to `App.tsx` or `index.tsx`

[test-admin.zip](https://github.com/vitejs/vite-plugin-react/files/10879740/test-admin.zip)

or

1. Create project with `yarn create vite test-admin --template react-ts`.
2. Open it with VSCode
3. Go to `App.tsx` or `index.tsx`

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 15.50 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Did you run `yarn install`?

**Comment by Mikilll94** [comment]
@ArnaudBarre 
I have run `yarn` to install packages.

It works when using `npm` but it is not working when using `yarn`.

**Comment by Mikilll94** [comment]
In `yarn` you don't run `yarn install` but just `yarn` to install packages.

**Comment by ArnaudBarre** [comment]
> In yarn you don't run yarn install but just yarn to install packages.
 
Yeah both are the same command, but not everyone know so I was explicit.

> It works when using npm but it is not working when using yarn.

You have something strange in your setup. the yarn lock contains reference to workspace but there is no configuration for that

**Comment by ArnaudBarre** [comment]
Closing for missing repro. Please provide a stackblitz repro if you think there an issue with the plugin.
