### ISSUE TITLE
HMR freezes browser when using react-router

### ISSUE THREAD

**Issue by caghand** [vitejs/vite-plugin-react#116]
### Describe the bug

If I change the contents of a functional component that's wrapped in react-router's `withRouter()`, or if I change any of the children of that component, then HMR kicks in, but the browser hangs, eventually resulting in out-of-memory.

This issue started happening in version 3.1.0.  It also started happening in @vitejs/plugin-react-swc in the same version.

Others have encountered the same issue, but with a different router:
https://github.com/TanStack/router/issues/532
https://github.com/TanStack/router/issues/510

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jvmb7t?file=src/App.jsx

### Steps to reproduce

Install the following dependencies:
```
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^3.1.0",
    "vite": "^4.1.4"
  }
```
Configure "@vitejs/plugin-react" in vite.config.js.
Wrap a functional component in `withRouter()`.
Launch the dev server and change the contents of the functional component.
Browser will hang, eventually resulting in out-of-memory.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 36.89 GB / 63.95 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - D:\<path_to_project>\node_modules\.bin\yarn.CMD
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.1 => 1.0.1
    @vitejs/plugin-react: 3.1.0 => 3.1.0
    vite: ^4.1.4 => 4.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
The issue is that you creating a component with a lower case and then re-exporting as an upper case so that the plugin things everything is fine but Babel did not apply fast refresh to the wrapper.

Change your code to `export const AppWithRouter = withRouter(App);` and update the import in main.jsx (I don't think there is any benefice to hide the wrapper with shadow name export)

**Comment by caghand** [comment]
Thanks @ArnaudBarre!  Sorry about the misleading issue title.  I had no idea that the root cause was my capitalization.
The problem is, I have hundreds of these re-export instances in my codebase.  It will be very tedious to fix them all, and in fact, I don't think I can prevent other developers in my team from creating similar re-exports in the future.
Are there any other solutions you can think of?  I am even OK with using a hacky patch-package for @vitejs/plugin-react.

**Comment by ArnaudBarre** [comment]
Ok found the culprit. This is due to the shadow rename (I still think this is a bad practice because it can confuse grep search and humans too). It will be fixed in the next release (see latest commit on main).

In the meantime you can apply the patch by changing line 19 of `node_modules/@vitejs/plugin-react/dist/refreshUtils.js` to `exports.register(exportValue, filename + ' export ' + key)`.

Edit: After investigation, this fix is safe.

**Comment by ArnaudBarre** [comment]
What you need to avoid in the meantime is the shadow export rename. Probably there is an eslint rule for that

**Comment by caghand** [comment]
Thanks @ArnaudBarre!  That patch works perfectly!  My team will really appreciate this.
And I've seen that you've applied the same patch to @vitejs/plugin-react-swc.  Thank you for that!
