### ISSUE TITLE
`@jsxImportSource` comment triggers vite:esbuild warning

### ISSUE THREAD

**Issue by targos** [vitejs/vite-plugin-react#12]
### Describe the bug

Using an `/** @jsxImportSource @emotion/react */` directive triggers a warning from the `vite:esbuild` plugin, which says that React's "automatic" JSX transform must be enabled.
The warning can be silenced with `esbuild: { jsx: 'automatic' }` in the Vite config, but according to the documentation of `@vitejs/plugin-react`, the automatic transform is supposed to be enabled by default.
I think the problem appeared with Vite 3 / plugin-react 2.

### Reproduction

https://github.com/targos/vite-plugin-react-warning

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 4.76 GB / 15.87 GB
  Binaries:
    Node: 18.2.0 - ~\AppData\Local\Volta\tools\image\node\18.2.0\node.EXE
    npm: 8.9.0 - ~\AppData\Local\Volta\tools\image\node\18.2.0\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
  npmPackages:
    @vitejs/plugin-react: ^2.0.1 => 2.0.1
    vite: ^3.0.7 => 3.0.7
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
> npm run build

> test-emotion@0.0.0 build
> vite build

vite v3.0.7 building for production...
transforming (3) src\main.jsx[plugin:vite:esbuild] The JSX import source cannot be set without also enabling React's "automatic" JSX transform
2  |  import reactLogo from './assets/react.svg';
3  |  import './App.css';
4  |  /** @jsxImportSource @emotion/react */
   |                       ^
5  |
6  |  import { css } from '@emotion/react';

✓ 62 modules transformed.
dist/assets/react.35ef61ed.svg   4.03 KiB
dist/index.html                  0.44 KiB
dist/assets/index.730dd8c4.css   1.71 KiB / gzip: 0.78 KiB
dist/assets/index.ce345959.js    262.50 KiB / gzip: 64.34 KiB
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by haoqunjiang** [comment]
Esbuild supported the React `automatic` JSX transform 19 days ago. https://github.com/evanw/esbuild/releases/tag/v0.14.51
`@vitejs/plugin-react` hasn't caught up yet.

**Comment by haoqunjiang** [comment]
I think aside from the unintended warning, the code transformation should still work correctly?

**Comment by targos** [comment]
Yes, the transformation is correct.

**Comment by patak-cat** [comment]
For reference, in case you would like to help @targos, there is ongoing work to use esbuild `automatic` JSX transform in this PR:
- https://github.com/vitejs/vite/pull/9590

**Comment by sapphi-red** [comment]
Closing as https://github.com/vitejs/vite/pull/9590 is release by plugin-react 3.0.0 and I confirmed the warning does not happen any more.
