### ISSUE TITLE
Cannot use JSX unless the '--jsx' flag is provided.

### ISSUE THREAD

**Issue by jitiendran** [vitejs/vite-plugin-react#124]
### Describe the bug

I am trying to create `vite-react` project using `yarn` as specified in [docs](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)

After creating when I try to create a component say `Note.tsx`  with contents

```tsx
const Note = () => {
  return <>something</>;
};

export default Note;
```

I am getting an error `Cannot use JSX unless the '--jsx' flag is provided.`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-lftt8j?file=sample/src/Note/Note.tsx

### Steps to reproduce

- Create vite react-ts  project using

  ```bash
  yarn create vite
  ```
- Create a component and write any `JSX or TSX` content

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    vite: ^4.2.0 => 4.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This seems to be an issue with having a extra top level folder inside stackblitz
Normally tsconfig should be at the route, but I don't succed to move things out of `/sample`

**Comment by jitiendran** [comment]
`tsconfig` file is in the root level of the project `sample` in stackblitz. 
And also this issue is reproducible in local as well but only If we create `vite-react-ts` project using `yarn`

**Comment by ArnaudBarre** [comment]
Have you installed the deps after creating the project?

**Comment by jitiendran** [comment]
Yes I have installed all dependencies after creating the project

**Comment by ArnaudBarre** [comment]
Just downloaded the project. dev & build are fine. Not errors either in websotrm and vs code.

**Comment by jitiendran** [comment]
`dev` and `build` runs fine only that the error is thrown in tsx file

**Comment by ArnaudBarre** [comment]
What IDE are you using locally?

**Comment by jitiendran** [comment]
vscode

**Comment by ArnaudBarre** [comment]
Sorry I can't repo. And there is probably hundreds of people trying yarn create vite react without other reports so this is most probably an issue in your setup

**Comment by jitiendran** [comment]
As observed I don't see more than half of the dependencies not getting installed. I guess mostly the problem is with my side.
So closing the ticket.
