### ISSUE TITLE
TypeError: Component is not a function when using export as syntax with styled-components

### ISSUE THREAD

**Issue by crtl** [vitejs/vite-plugin-react#125]
### Describe the bug

When exporting styled component with `export as` syntax the app will render on first launch (browser refresh) but HMR will crash with `Component is not a function` error.

```ts
import styled from 'styled-components';

const TestComponent = () => <h1>Test component</h1>;

const StyledTestComponent = styled(TestComponent)`
    color: blue;
`;

export { StyledTestComponent as TestComponent };
```

```
react-dom_client.js?v=9f1a4444:12169 Uncaught TypeError: Component is not a function
    at renderWithHooks (react-dom_client.js?v=9f1a4444:12169:26)
    at mountIndeterminateComponent (react-dom_client.js?v=9f1a4444:14919:21)
    at beginWork (react-dom_client.js?v=9f1a4444:15900:22)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=9f1a4444:3672:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=9f1a4444:3697:24)
    at invokeGuardedCallback (react-dom_client.js?v=9f1a4444:3731:39)
    at beginWork$1 (react-dom_client.js?v=9f1a4444:19759:15)
    at performUnitOfWork (react-dom_client.js?v=9f1a4444:19192:20)
    at workLoopSync (react-dom_client.js?v=9f1a4444:19131:13)
    at renderRootSync (react-dom_client.js?v=9f1a4444:19110:15)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4eqtiy

### Steps to reproduce

1. Go to reproduction URL
2. Run app, it will render
3. Edit `App.tsx` or `test-component.tsx` to trigger HMR
4. App will crash and console shows error

### System Info

```shell
See stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Yep this is an issue when the name of the exported component shadow the name of a component in the file.
This has been fixed on [main](https://github.com/vitejs/vite-plugin-react/commit/a74dfefc14734009d3e259a1b0dc4e4967dcb709), should be released this week

**Comment by ArnaudBarre** [comment]
The commit is now included in the new beta version (should be stable next week)
