### ISSUE TITLE
[@vitejs/plugin-react] React 18's `bootstrapModules` option incompatible with Vite's React plugin

### ISSUE THREAD

**Issue by jplhomer** [vitejs/vite-plugin-react#14]
### Describe the bug

React 18 introduces a [new `renderToPipeableStream` pattern](https://github.com/reactwg/react-18/discussions/37), which includes options for adding client entrypoints via `bootstrapScripts` and `bootstrapModules`:

```js
renderToPipeableStream(
  <App />,
  {
    bootstrapModules: ["src/main.jsx"],
  }
).pipe(response);
```

Script tags generated from these options include the `async` property. This allows React to progressively hydrate the document as it streams in.

Unfortunately, this is incompatible with the React Refresh header added in `@vitejs/plugin-react`. I assume this is because the header code throws an Error if it cannot detect the preamble (which is still loaded eventually, just not asynchronously):

```
Html.jsx:6 Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at Html.jsx:6:11
(anonymous) @ Html.jsx:6
client.ts:52 
```

It's odd that I cannot reproduce this behavior by simply adding `async` to the script tag in the React starter template: https://stackblitz.com/edit/vitejs-vite-fpvd7t?file=index.html

But I can when it's included via `bootstrapModules`: https://github.com/jplhomer/vite-streaming-ssr-demo/pull/3

Perhaps this means that the way React is injecting the script makes it execute earlier than it normally does? I'm kind of stumped.

Not sure what the best approach to solving this is! I think it's important that entrypoint scripts can be `async` to support streaming SSR in React 18.

Should we to update the injected header to more gracefully wait for the RefreshRuntime to be available?

### Reproduction

https://github.com/jplhomer/vite-streaming-ssr-demo/pull/3

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 133.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4 
    vite: ^2.7.13 => 2.7.13
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyco130** [comment]
It _seems_ to work when I add the `async` attribute to the preamble script.

**Comment by Trackhe** [comment]
Do you know what i missed? Because i cant get SSR working with the Production build: https://github.com/Trackhe/Vite-React-SSR-HMR
https://github.com/vitejs/vite/issues/8449

**Comment by b3nten** [comment]
> It _seems_ to work when I add the `async` attribute to the preamble script.

Doesn't seem to be working for me unfortunately. The workaround seems to be loading the script as part of the stream.

**Comment by letientai299** [comment]
I hit this same problem and managed to find [a work around](https://github.com/letientai299/vite-react-ssr-typescript/blob/master/src/refresh-hack.js). I put together a demo below. Perhaps someone with more knowledge on Vite could derives a proper solution to make React SSR more straight forward with Vite.

https://github.com/letientai299/vite-react-ssr-typescript

**Comment by ArnaudBarre** [comment]
Hi everyone!

I currently investigate open issues to work on a new API for the next major. I understand that there is an issue with `renderToPipeableStream` and script loading order, but I don't see any quick reproduction to look at it (only a closed PR on repo)

Can someone provide a small reproduction of the issue? Thanks
