### ISSUE TITLE
how to import libraries with .js extensions?

### ISSUE THREAD

**Issue by aizaz-sparkai** [vitejs/vite-plugin-react#140]
### Describe the bug

I'm using neovis.js library in react vite but vite doesn't allow .js imports.

my import is:
`import NeoVis, { NEOVIS_ADVANCED_CONFIG } from 'neovis.js';`

and got this error:

``` [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/neovis.js/dist/neovis-without-dependencies.js:1:216:
      1 │ ...t"),require("core-js/modules/web.dom-collections.iterator.js"),require("...
        ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to
  exclude it from the bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of
  bundle-time.```

Can we achieve that is vite and any other solution for achieve such thing in vite.



### Reproduction

https://stackblitz.com/edit/vitejs-vite-5ou5xx?file=package-lock.json,package.json,src%2FApp.jsx&terminal=dev

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 199.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: 2022.12.12.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.0 => 3.0.1 
    vite: ^4.0.0 => 4.0.4
```

### Used Package Manager

yarn 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [ ] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi,

You missed the first line of the error: `Could not resolve "core-js/modules/web.dom-collections.iterator.js"`

The issue is not the `.js` but the fact that the lib depend on `core-js` without adding it as a dependency.
I don't know the lib but that's both bad and outdated to explicitly depends on core-js.

Vite by default targets es2020 which means that you a subset of JS feature large enough to not require polyfill.

**Comment by aizaz-sparkai** [comment]
what should i do for import that kind of library? @ArnaudBarre

**Comment by ArnaudBarre** [comment]
This is clearly a problem on the library side. Their "module" entries contains require calls.
You can fix this upsteam, patch the lib or re-compile a moden version of it from source.

You can core-js as a dep of your project, but seeing how bad their "module" entry point, I'm not sure this is enough.
If this is still not working, you can switch to a better bundled lib of keep using webpack based tools that would be able to handle this kind of wrong esm
