### ISSUE TITLE
React 项目使用 less css module  文件更新后 Dom 样式未更新

### ISSUE THREAD

**Issue by Wxh16144** [vitejs/vite-plugin-react#142]
### Describe the bug

我往 [复现仓库](https://github.com/Wxh16144/vite-react-HMR-bug-report) 推送了[vitejs](https://github.com/Wxh16144/vite-react-HMR-bug-report/tree/nextjs) 和 [nextjs](https://github.com/Wxh16144/vite-react-HMR-bug-report/tree/nextjs) 两个分支 以方便开发者/维护者复现。两者均有一个 `sheard/components/Test` 目录，并且逻辑是一样的。

### Reproduction

https://github.com/Wxh16144/vite-react-HMR-bug-report

### vite( actually happening)
https://user-images.githubusercontent.com/32004925/229674880-1018905e-c1da-4e9a-af9b-22ea61654bd2.mp4

### nextjs(expected)
https://user-images.githubusercontent.com/32004925/229674900-2b698a7b-047e-4784-ae1d-97ccd5d51ba2.mp4

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.91 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi,
Thanks for taking the time to simplify the issue to a small reproductible example that I can reproduce. But now the code doesn't really make sense, caching components inside useMemo is quite exotic, and it's quite expected that this can break fast refresh.

That's cool if it works with nextjs, and maybe there is something off in the fats refresh implementation of this plugin, but I don't think this usecase justify looking into it (you can prove me wrong by sending some official documentation explaining this patten)
