### ISSUE TITLE
Cannot run vite app on port 80

### ISSUE THREAD

**Issue by lexuantunght** [vitejs/vite-plugin-react#145]
### Describe the bug

When I specify port = 80
- add --port 80 to scripts
- config port: 80 in vite config
I run on macOS with sudo npm run dev but received error

error when starting dev server:
Error: listen EACCES: permission denied 127.0.0.1:80
    at Server.setupListenHandle [as _listen2] (node:net:1355:21)
    at listenInCluster (node:net:1420:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1559:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8)

### Reproduction

vite.new/react

### Steps to reproduce

1. Change port to 80
2. Run dev

### System Info

```shell
MacOS - Ventura 13 - Intel Chip
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I think port 80 is reserved on mac OS. I'm using Mac OS and I don't see an issue, you can literally use any other port.

If you absolutely want to use this port, please search on the internet for more information about port 80 in used, there is nothing specific to Vite with that issue
