### ISSUE TITLE
Support fast refresh in workers

### ISSUE THREAD

**Issue by itsdouges** [vitejs/vite-plugin-react#152]
### Description

Currently this plugin assigns variables to `window` - which is unavailable inside workers. If instead we targeted `globalThis` as [an alternative](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) [...The globalThis property provides a standard way of accessing the global this value (and hence the global object itself) across environments.] that would be a way forward where the same code can function in both a DOM and worker environment.

### Suggested solution

Replace all `window` usage with `globalThis`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
Do you React components inside your worker files?

**Comment by itsdouges** [comment]
There's an experimental react three fiber api that runs scenes inside a worker, to simplify the model react is ran inside there as well.

That's why you see in another thread folks wanting to be able to disable fast refresh in 4.0. A better alternative is to keep it working imo.

**Comment by ArnaudBarre** [comment]
Yeah but that's not trivial, you need to inject the fast refresh runtime exactly one per worker, and before any component run.

Can you provide a small setup with a component running inside a worker with a state so I can experiment with it?

Does react three fiber recommend using only one worker or multiple?

**Comment by itsdouges** [comment]
@drcmda would you be able to create one?

**Comment by drcmda** [comment]
@ArnaudBarre here's a vite example. https://github.com/pmndrs/react-three-offscreen/tree/main/examples/vite

due to https://github.com/vitejs/vite-plugin-react/issues/151 it only works with plugin-react@3.1.0 atm.

**Comment by ArnaudBarre** [comment]
Thanks I will look into it to understand why #151 happens.

For the feature request here, I will need to know if using multiple workers doing offscreen render is expected or not?

**Comment by drcmda** [comment]
thanks arnaud! i think not. it would be to allow a react root to run off the main thread and the result of its view is sent into a offscreen canvas. im guessing most react canvas renderers will only require a single worker, react-konva, react-skia, babylon, pixi, etc.

**Comment by siefkenj** [comment]
I just encountered this issue. I am using React in a webworker to statically render markup via ReactDOM, and this plugin is currently crashing my webworker by using `window`. It would be neat to support refreshing in webworkers, but at a minimum, I would hope that the plugin could self-disable to avoid erroring in a webworker.

**Comment by ArnaudBarre** [comment]
The assignment for window is now behind a check to not fail inside workers. The support for Fast refresh in web worker requires first Vite support for HMR inside web web workers: https://github.com/vitejs/vite/issues/5396

I'm closing this for now, this update of the plugin will be straight forward if the feature lands into core (There is a stale but interesting draft PR for this)
