### ISSUE TITLE
Can not work with core-js by .babelrc & .browserslistrc

### ISSUE THREAD

**Issue by jerrywu001** [vitejs/vite-plugin-react#153]
### Describe the bug

For example, if I use `''.padStart` with .browserlistrc `>0.2%`, It should be auto polyfill with `babel-preset-env`.

The result should be:
 [demo with @rollup/plugin-babel is ok](https://stackblitz.com/edit/vitejs-vite-7gfghf?file=.browserslistrc,.babelrc,src%2Ftest.ts,vite.config.ts):

![image](https://user-images.githubusercontent.com/12525415/234176767-1ff7c941-0cb3-479c-96e4-45412d6e4bee.png)

**But there is no polyfill with core-js.**

![image](https://user-images.githubusercontent.com/12525415/234177070-977f91e8-7101-47e7-9d13-b419d5ae6b54.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vv1mvv?file=src%2Ftest.ts,.browserslistrc,.babelrc,vite.config.ts

### Steps to reproduce

- npm install
- npm run build
- then open dist/index.[hash].js

Has no polyfill with core-js.

![image](https://user-images.githubusercontent.com/12525415/234177070-977f91e8-7101-47e7-9d13-b419d5ae6b54.png)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^4.0.0-beta.0 => 4.0.0 
    @vitejs/plugin-react-swc: ^3.3.0 => 3.3.0 
    vite: ^4.3.1 => 4.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Polyfill is currently outside of the scope of this module. Maybe https://www.npmjs.com/package/@vitejs/plugin-legacy will do what you need

**Comment by jerrywu001** [comment]
> Polyfill is currently outside of the scope of this module.

Building with @vitejs/plugin-legacy is very slow. 🤣

Can move this issue to `discussions`? @ArnaudBarre

**Comment by ArnaudBarre** [comment]
How do you expect this to be less slow with this plugin?

**Comment by jerrywu001** [comment]
> How do you expect this to be less slow with this plugin?

The previous packaging time was 2m, but it was used for `legacy plugin`, and it became 6m

**Comment by ArnaudBarre** [comment]
Yeah but it's slower because you run Babel on source code and need more work on it.

Maybe swc can help you have good polyfill while keeping build "fast". (but this is also outside of the scope of the official plugin) 

Unrelated: have you tried Vite 4.3 to improve build perf?

**Comment by ArnaudBarre** [comment]
Closing as out of scope
