### ISSUE TITLE
Fast refresh doesn't work when we use "js" files instead of "jsx" files and there isn't "import React"

### ISSUE THREAD

**Issue by joaostroher** [vitejs/vite-plugin-react#155]
### Describe the bug

I have a project where we use JS files instead of JSX files. When files without the "import React" are changed, the fast refresh doesn't work. We expect the fast refresh work even without the  "import React", since it is not required anymore.
The issue seems to be here: https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts#L168-L174

### Reproduction

https://stackblitz.com/edit/vitejs-vite-y13hlt?file=src%2FComponent1.js,src%2FComponent2.js

### Steps to reproduce

Run "npm run install" followed by "npm run dev". 

- If you edit the "Component1.js" file (it doesn't have the "import React"), you'll see on the console `[vite] page reload src/Component1.js`, and the page is reloaded.
- If you edit the "Component2.js" file (it has the "import React"), you'll see on the console `[vite] hmr update /src/Component2.js`, and the page is not reloaded.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0 
    vite: ^4.3.2 => 4.3.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Yeah this expected. I think this is a bad practice that CRA created to put jsx inside js file.
Running fast-refresh on js files in case there is component will slow down the dev server for people using the default setup, so we won't change this.

You can use this gist https://gist.github.com/parties/90cdf35f9a3d05bea6df76dc83a69641 to help you migrate existing codebases
