### ISSUE TITLE
It takes too long to build, but I don't know the cause It doesn't show up in the console log

### ISSUE THREAD

**Issue by mineclover** [vitejs/vite-plugin-react#159]
### Describe the bug

I am making a blog with a vite

Dev works fast, but it takes a very long time to build 
I want to know the cause

### Reproduction

https://github.com/mineclover/vite-prototype-blog

### Steps to reproduce

npm i
npm run build

I've been building for 20 minutes

There is a dependency but it is not relevant to this issue
Uploading to netlify fails build due to build timeout

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 14.11 GB / 31.86 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.138
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1       
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.1 => 1.0.1
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    vite: ^4.3.1 => 4.3.1
```

### Used Package Manager

npm

### Logs

> react-playground@0.0.0 buildtest      
> tsc && vite build --debug

  vite:config bundled config file loaded in 427.42ms +0ms
  vite:config using resolved config: {  
  vite:config   plugins: [
  vite:config     'vite:ensure-watch',  
  vite:config     'vite:build-metadata',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:pre-alias',     
  vite:config     'alias',
  vite:config     'vite:react-babel',   
  vite:config     'vite:react-refresh', 
  vite:config     'vite:react-jsx',     
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',       
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',       
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',   
  vite:config     'vite:worker',        
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback', 
  vite:config     'vite:define',        
  vite:config     'vite:css-post',      
  vite:config     'vite:build-html',    
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:ensure-watch',  
  vite:config     'commonjs',
  vite:config     'vite:data-uri',      
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',   
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',        
  vite:config     'vite:reporter',      
  vite:config     'vite:load-fallback'  
  vite:config   ],
  vite:config   resolve: {
  vite:config     mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
  vite:config     browserField: true,   
  vite:config     conditions: [],       
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',     
  vite:config       '.mts',  '.ts',     
  vite:config       '.jsx',  '.tsx',    
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object], [Object] ]
  vite:config   },
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',       
  vite:config     assetsDir: 'assets',  
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,   
  vite:config     sourcemap: false,     
  vite:config     rollupOptions: {},    
  vite:config     minify: 'esbuild',    
  vite:config     terserOptions: {},    
  vite:config     write: true,
  vite:config     emptyOutDir: null,    
  vite:config     copyPublicDir: true,  
  vite:config     manifest: false,      
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,   
  vite:config     ssrEmitAssets: false, 
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit:
 500,
  vite:config     watch: { buildDelay: 10000 },
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },   
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true },
  vite:config     cssMinify: true       
  vite:config   },
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',    
  vite:config     force: undefined,     
  vite:config     include: [ 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react' ],
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   esbuild: {
  vite:config     jsxDev: false,        
  vite:config     jsx: 'automatic',     
  vite:config     jsxImportSource: undefined,
  vite:config     jsxSideEffects: false 
  vite:config   },
  vite:config   configFile: 'P:/Dev/react-playground/vite.config.ts',
  vite:config   configFileDependencies: [ 'P:/Dev/react-playground/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,      
  vite:config     base: undefined,      
  vite:config     mode: undefined,      
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,  
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force:
 undefined },
  vite:config     build: {}
  vite:config   },
  vite:config   root: 'P:/Dev/react-playground',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: 'P:\\Dev\\react-playground\\public',
  vite:config   cacheDir: 'P:/Dev/react-playground/node_modules/.vite',
  vite:config   command: 'build',       
  vite:config   mode: 'production',     
  vite:config   ssr: {
  vite:config     format: 'esm',        
  vite:config     target: 'node',       
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }    
  vite:config   },
  vite:config   isWorker: false,        
  vite:config   mainConfig: null,       
  vite:config   isProduction: true,     
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,      
  vite:config     strictPort: undefined,
  vite:config     host: undefined,      
  vite:config     https: undefined,     
  vite:config     open: undefined,      
  vite:config     proxy: undefined,     
  vite:config     cors: undefined,      
  vite:config     headers: undefined    
  vite:config   },
  vite:config   envDir: 'P:/Dev/react-playground',
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,     
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {  
  vite:config     'fnpd_P:/Dev/react-playground' => {
  vite:config       dir: 'P:\\Dev\\react-playground',
  vite:config       data: [Object],     
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',       
  vite:config     plugins: [
  vite:config       'vite:ensure-watch',
  vite:config       'vite:build-metadata',
  vite:config       'vite:watch-package-data',
  vite:config       'vite:pre-alias',   
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',     
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',     
  vite:config       'vite:json',        
  vite:config       'vite:wasm-helper', 
  vite:config       'vite:worker',      
  vite:config       'vite:asset',       
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',      
  vite:config       'vite:css-post',    
  vite:config       'vite:build-html',  
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:force-systemjs-wrap-complete',
  vite:config       'vite:ensure-watch',
  vite:config       'commonjs',
  vite:config       'vite:data-uri',    
  vite:config       'vite:worker-post', 
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob', 
  vite:config       'vite:build-import-analysis',
  vite:config       'vite:esbuild-transpile',
  vite:config       'vite:terser',      
  vite:config       'vite:load-fallback'
  vite:config     ],
  vite:config     rollupOptions: {},    
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]        
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +14ms
vite v4.3.1 building for production...

watching for file changes...

build started...
  vite:esbuild 109.33ms tsconfck init P:/Dev/react-playground +0ms
✓ 172 modules transformed.
dist/index.html                  0.40 kB │ gzip:   0.28 kB
dist/assets/index-c9e30fe8.js  382.85 kB │ gzip: 128.73 kB
built in 2882ms.
.
.
.
The work isn't done, but it doesn't go any further

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Seems like you've activated the watch mode by mistake?

**Comment by mineclover** [comment]
> Seems like you've activated the watch mode by mistake?

Do you have a point where I activated the watch mode?
This is my build script
"build": "tsc && vite build",

**Comment by mineclover** [comment]
> Seems like you've activated the watch mode by mistake?



> 
Do you have a point where I activated the watch mode?
This is my build script
"build": "tsc && vite build",

**Comment by ArnaudBarre** [comment]
Does removing the watch option from the config change something?

**Comment by mineclover** [comment]
I fully understood
I have now deleted the code below
This code was put in because the hot reload happened too often.
Thank you so much for erasing
```
build: {
    watch: {
      buildDelay: 10000,
    },
  },
```
