### ISSUE TITLE
vite v4.3.5 doesn't work on windows

### ISSUE THREAD

**Issue by topdeveloper424** [vitejs/vite-plugin-react#160]
### Describe the bug

``npm create vite@latest my-react-app -- --template react``
``cd my-react-app``
``npm install``
``npm run dev``

then it shows 
![image](https://github.com/vitejs/vite-plugin-react/assets/40516126/e296947e-a3d0-44b8-8e01-121aa0087e50)
But when I open in browser,
![image](https://github.com/vitejs/vite-plugin-react/assets/40516126/637daada-bef5-4ec4-b54b-08dcf59c8bb3)

what is the issue?

### Reproduction

http://localhost:5173/

### Steps to reproduce

``npm create vite@latest my-react-app -- --template react``
``cd my-react-app``
``npm install``
``npm run dev``

### System Info

```shell
Windows 10
node version v18.14.0
npm version 9.4.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi, we have test suite that ensure that some basic setup works on common OS.
Given also no other report/like of this issue in two days I think this is an issue on your setup

**Comment by topdeveloper424** [comment]
no, it's not on my setup.  I clearly showed the issue.  I tried many times, but same
