### ISSUE TITLE
Migrating from react without a single error message

### ISSUE THREAD

**Issue by dellwatson** [vitejs/vite-plugin-react#161]
### Describe the bug

Hello im migrating my create-react-app to vitejs. it's been pain in the hell to debug part by part without knowing the error message. 

at first, it was because of process.env. taking so much time split code 1by1 to identify what's wrong, then simply update the define process.env
but still many issue, and leave my page into a blank page.
this my vite.config.ts
```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  // plugins: [react()],
  plugins: [
    react({
      jsxRuntime: "automatic",
    }),
  ],
  esbuild: {
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
  },
  server: {
    hmr: {
      overlay: false,
    },
  },
  define: {
    "process.env": {},
  },
});

```

now the recent issue is using react/emotion. there's still no error at all identifying the issue. i noticed it by looking at the devtools element on the class 
```js
<div css="You have tried to stringify object returned from `css` function. It isn't supposed to be used directly (e.g. as value of the `className` prop), but rather handed to emotion so it can handle it (e.g. as value of `css` prop)."></div>
```

there's apollo provider, and web3 problem. 
i have turned off/on the hmr, and nothing works. give me blank page without a single error message. I'm coding blidnly.

### Reproduction

https://github.com/free-fork/vite-migration

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.78 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Desktop/pix/pix-dashboard-vite/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 113.0.5672.92
    Chrome Canary: 115.0.5763.0
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0 
    vite: ^4.3.2 => 4.3.5
```

### Used Package Manager

yarn

### Logs

running on blank page, no error message but still able to build the page:

```js
yarn run v1.22.19
$ vite build 
vite v4.3.5 building for production...
✓ 401 modules transformed.
dist/index.html                               0.46 kB │ gzip:   0.30 kB
dist/assets/luckcattitle-df9287dc.png        14.83 kB
dist/assets/corporation1title-b7cd09d3.png   15.63 kB
dist/assets/landmark-0ffd4c2d.png            28.92 kB
dist/assets/newlands-e2a41ffb.png            47.34 kB
dist/assets/corporation1-f35e4891.png        63.89 kB
dist/assets/y-3491270a.png                   74.49 kB
dist/assets/luckcat-9c5016d3.png             74.94 kB
dist/assets/Druk-Wide-Bold-0ea32bed.otf     116.67 kB
dist/assets/Druk-Wide-Medium-bcad4f89.otf   167.95 kB
dist/assets/index-f7bcba11.css               13.43 kB │ gzip:   3.01 kB
dist/assets/index-0608e794.js               623.48 kB │ gzip: 195.81 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 1.64s
✨  Done in 2.27s.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi, please provide a reproduction: https://antfu.me/posts/why-reproductions-are-required

A lot of your config seems not very classic. If you're suing emotion you should probably use the [jsximportsource](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#jsximportsource) option

**Comment by dellwatson** [comment]
this is the updated reproduction:

env is included, nothing is critical

fixing 1 issue and another issue comes. it's like building new app now. 
im already in pain looking at the spaghetti code from prev devs, this is max pain now.

i did update :
```js
// https://vitejs.dev/config/
export default defineConfig({
  // plugins: [react()],
  plugins: [
    react({
      // jsxRuntime: "automatic",
      jsxImportSource: "@emotion/react",
      babel: {
        plugins: ["@emotion/babel-plugin"],
      },
    }),
    svgr(),
  ],
  esbuild: {
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
  },
  server: {
    hmr: {
      overlay: false,
    },
  },
  define: {
    "process.env": {},
  },
});

```

but it's not just emotion issue, process.env, svgr, but there's nothing in error message, if you uncomment one of these. you can see byurself. no error message. 
i litterally need 1by1 hide component, part by part to find out the exact issue
