### ISSUE TITLE
Not able to use postcss-import. Giving error ->Unable to resolve `@import "variables.css"`

### ISSUE THREAD

**Issue by siddhantchopra** [vitejs/vite-plugin-react#164]
### Describe the bug

Im trying to migrate my project to vitejs and having an issue with postcss-imports. While running the project, and configuring postcss using vite.config.js for postcss import. The css files are not working
Here is my code-snippet

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import atImport from 'postcss-import';

export default defineConfig({
  plugins: [
    react(),
  atImport({
      path: ['src/themes/config/variables.css'],
      resolve: (id, baseDir, importOptions) => {
        console.log(id, baseDir, importOptions);
      },
    })
  ]
});

Please let me know what I'm doing wrong so that I can fix this issue

Node version: 18.16.0
These are my modules installed for the project
    "postcss": "^8.4.23",
    "postcss-cli": "^10.1.0",
    "postcss-cssnext": "^3.1.1",
    "postcss-import": "^15.1.0",
    "postcss-syntax": "^0.36.2",
    
![error](https://github.com/vitejs/vite-plugin-react/assets/30842286/aea2e305-2a64-414e-9232-6c3d8167efef)

### Reproduction

//

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 1.94 GB / 15.81 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.0 => 3.3.0
    vite: ^4.3.0 => 4.3.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
postcss with import are supported by default by Vite. You should not need any changes to your config and no need to install all this as a peer deps. Just use a relative path `@import "./variables.css"`

**Comment by siddhantchopra** [comment]
This is not I'm are looking for, I need to configure base path for my common css which i can use thought out the application like this **@import "variables.css** 

Please help us out in configuring it via vite.config.js or postcss.config.js
`                postcssImport({
                  path: ['/src/themes/config/variables.css']
                }),`

**Comment by ArnaudBarre** [comment]
I'm not sure why you need to import this file so many times, one import per CSS bundle should be enough, which in most application I advised to be one if you use a utility classes based CSS framework.

You can look into https://vitejs.dev/config/shared-options.html#resolve-alias to remap import in Vite.

Anyway this issue as nothing to do with this plugin, and I really invite you to reconsider spending so much time configuring imports instead of using relative imports than any future you use will understand without any configuration.
