### ISSUE TITLE
Refreshing the entry throws a react createRoot error

### ISSUE THREAD

**Issue by ChillyBots** [vitejs/vite-plugin-react#173]
### Describe the bug

It's possible to throw an error at the root of the app by trying to hot reload the file with ReactDOM.createRoot:

`Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.`

This also leads to a black screen of death as [discussed here](https://stackoverflow.com/questions/76297888/react-vite-hmr-is-breaking-the-app-the-page-goes-blank/76412974#76412974), however, I cannot reliably reproduce that, I'll update if I manage to reproduce it in stackblitz

### Reproduction

https://stackblitz.com/edit/vitejs-vite-p5ihy2?file=src%2Fmain.tsx

### Steps to reproduce

Edit the main.tsx file, observe the console

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 37.65 GB / 63.73 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 3.2.4 - ~\Documents\portal2\node_modules\.bin\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I did 10-20 HMR in a row without any error. Even is there was an issue, given that this pattern leads to not being able the HMR the main component, I wont try to support it. This leads to bad DX just to save one file in a project.
If you want have only one file App, just don't use the plugin and you will get full page reload each time.

If you have a reproduction that throw on HMR and don't break this rule of non putting aside the createRoot with a component, please open a new issue
