### ISSUE TITLE
 Identifier 'Buffer' has already been declare

### ISSUE THREAD

**Issue by stackcraft55** [vitejs/vite-plugin-react#180]
### Describe the bug

I am using the vite for react project
But I am having below issue
Uncaught SyntaxError: Identifier 'Buffer' has already been declared (at @heliofi_react.js?v=dac45cfc:62697:5)
How can I solve this?
Please help me
Looking forward to hearing from you soon
Thank you

### Reproduction

nothing now

### Steps to reproduce

npm run dev

### System Info

```shell
OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 8.15 GB / 19.84 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - F:\project\GOTM\GOTM\dev\update\gotm_front_app\node_modules\.bin\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.1.0
    @vitejs/plugin-react-swc: ^3.0.0 => 3.3.2
    vite: ^4.0.0 => 4.3.9
```

### Used Package Manager

npm

### Logs

F:/project/GOTM/GOTM/dev/update/gotm_front_app/node_modules/ethereum-cryptography/keccak.js +5ms
  vite:resolve 3.32ms process/ -> F:/project/GOTM/GOTM/dev/update/gotm_front_app/node_modules/process/browser.js +45ms
  vite:resolve 9.23ms abort-controller -> F:/project/GOTM/GOTM/dev/update/gotm_front_app/node_modules/abort-controller/browser.js +15ms
  vite:resolve 9.53ms jsonify -> F:/project/GOTM/GOTM/dev/update/gotm_front_app/node_modules/jsonify/index.js +0ms
  vite:deps Dependencies bundled in 7022.87ms +0ms

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Can't help you without a small reproduction. Probably an issue with a library that uses some node builtins
