### ISSUE TITLE
Components in pre-bundled packages ( optimizeDeps.include ) do not work with automatic JSX runtime ( @vitejs/plugin-react )

### ISSUE THREAD

**Issue by eddeee888** [vitejs/vite-plugin-react#19]
### Describe the bug

If we mark a package to pre-bundle with `optimizeDeps`, all components from the package must have `import React` statements even if `@vitejs/plugin-react` is used.

Hopefully this is something that can be fixed because it's fairly annoying to add `import React` statements in some files and not others. Also, the error would only happen at runtime IF the pre-bundled package is imported. This make it hard to find, especially in bigger projects.

In the provided reproduction repo, the app throws error at runtime saying `Word`, `Is` and `Bird` components do not have `import React` statements. To fix the problem, a user would have to:
a. Add `import React` statements to every component under `src/ui`
b. Remove `@/ui` at `config.optimizeDeps.include[0]` which defeats the benefits of pre-bundling, resulting in 4 separate requests instead of 1.

### Reproduction

https://stackblitz.com/edit/vite-wkudpx?file=README.md

### System Info

```shell
Local env:

System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.36 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.1
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.4
    vite: ^2.7.2 => 2.7.10
```

Reproduction repo:
```
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.4 
    vite: ^2.7.2 => 2.7.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi!
That's interesting to see someone using `optimizeDeps` for source code. This is not officially supported cc @patak-dev

I just tested and this make all the @ui package totally stale without a restart --force.

What is the goal of this optimisation? Are hitting some performance issue on a large project?

**Comment by a-type** [comment]
I have a use case for this since I recently extracted common UI components in https://github.com/a-type/gnocchi into a `packages/ui` shared module in my monorepo. The way I have things set up, shared packages are loaded as TS source directly using composite projects, not transpiled.

Moving the UI components into a separate module has proved problematic, since now each individual module file is being loaded over the network all at once on a page reload, causing a request waterfall/bottleneck during development. I was hoping to be able to combine all these into one request.

I'm not really sure how this behavior differs from what happens if those files were back in the original app source directory, but I definitely noticed the change after moving them.

**Comment by ArnaudBarre** [comment]
Yes this plugin has some strange behaviour if the files are coming from the project source or from the monorepo. I will remove this in the next major.

The "problem" of network is in fact not one: https://github.com/ArnaudBarre/esm-dev-server-limit
This is just showing that processing files is slow, but the network is not the issue in local.

If you're not using Babel plugins, I would advice to try the SWC plugin, which should allow you to use your ui package as if they were in your app source code with fast refresh and faster cold start

**Comment by ArnaudBarre** [comment]
We re-discussed with the team the idea of prebundling for source code. We are not sure now about a support in core but @antfu is experimenting with this https://github.com/antfu/vite-plugin-prebundle. You can try it out and follow the progress!
