### ISSUE TITLE
Uncaught ReferenceError: React is not defined caused by a node_modules tsx file even integrated @vitejs/plugin-react in vite.config.js

### ISSUE THREAD

**Issue by leejunhui** [vitejs/vite-plugin-react#192]
### Describe the bug

Hi, I rencently try to migrate my cra+webpack project to vite project.And when I have finished the transition work, I use `pnpm run dev` which corresponds to `dev: vite dev` to start my project.I encountered an error which stated like this:

```
Table.tsx:96 Uncaught ReferenceError: React is not defined
    at Table (Table.tsx:96:30)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
    at workLoopSync (react-dom.development.js:22707:5)
```

The `Table.tsx` is a custom react component from node_modules which is a dependency from our private repo.
After some digging and research, the most likely workaround is to add `@vitejs/plugin-react` and integrate it in `vite.config.js`, but I already done this.And the other workaround is to mannually add `import React from 'react`` which I think is not an ideal solution because of the repetitive and waste of time.

FYI: this is part of my my webpack.config.js, the `Table.tsx` is located in the `@yunti-private/*` package
```
            // Process application JS with Babel.
            // The preset includes JSX, Flow, TypeScript, and some ESnext features.
            {
              test: /\.(js|mjs|jsx|ts|tsx)$/,
              include: [paths.appSrc, ...paths.packages, /@yunti-private/],
              loader: require.resolve("babel-loader"),
              options: {
                customize: require.resolve(
                  "babel-preset-react-app/webpack-overrides"
                ),
                presets: [
                  [
                    require.resolve("babel-preset-react-app"),
                    {
                      runtime: hasJsxRuntime ? "automatic" : "classic",
                    },
                  ],
                ],

                plugins: getBabelPlugins(),
                // This is a feature of `babel-loader` for webpack (not Babel itself).
                // It enables caching results in ./node_modules/.cache/babel-loader/
                // directory for faster rebuilds.
                cacheDirectory: babelLoaderCacheDirectoryPath,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                compact: isEnvProduction,
              },
            },
```

And this is my `vite.config.js`

```
export default defineConfig(({ command, mode, ssrBuild }) => {
  return {
    optimizeDeps: {
      include: ['react', 'react-dom'],
    },
    plugins: [
      react({
        babel: {
          plugins: [
            ['@babel/plugin-proposal-decorators', { legacy: true }],
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            [
              '@babel/plugin-transform-runtime',
              {
                helpers: true,
                regenerator: true,
              },
            ],
          ],
        },
      }),
      wasm(),
      topLevelAwait(),

      // fix: requirer is not defined
      viteRequire(),
      pluginRewriteAll(),
      // svgr options: https://react-svgr.com/docs/options/
      svgr({ svgrOptions: { icon: true } }),
    ],
    server: {
      open: true,
    },
    build: {
      sourcemap: true,
    },
    css: {
      preprocessorOptions: {
        less: {
          math: 'always',
          relativeUrls: true,
          javascriptEnabled: true,
        },
      },
    },
  };
});
```

part of package.json

```json
{
    "vite": "4.3.9",
    "@vitejs/plugin-react": "4.0.0",
    "vite-plugin-top-level-await": "1.3.0",
    "vite-plugin-wasm": "3.2.2",
    "vite-require": "0.2.3",
    "vite-plugin-rewrite-all": "1.0.1",
    "vite-plugin-svgr": "3.2.0",
    "vite-plugin-babel": "1.1.3",
 }
```

### Reproduction

https://github.com/leejunhui/vitejs-vite-khqawl

https://stackblitz.com/edit/vitejs-vite-khqawl

#### Git Repo
1.Just clone the `https://github.com/leejunhui/vitejs-vite-khqawl` sample project.
2.And then run `pnpm i`.
3.Then run `pnpm run dev`.
4.And the error will output `Uncaught ReferenceError: React is not defined`

#### Stackblitz
just open [https://stackblitz.com/edit/vitejs-vite-khqawl](stackblitz)

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 43.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 112.0.2
    Safari: 16.5
    Safari Technology Preview: 17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LaurenceHo** [comment]
I am running into the same issue. Once I downgrade it to v3, the issue would be gone.

**Comment by leejunhui** [comment]
@LaurenceHo Hi, are you just downgrade the vite-plugin-react to v3 to solve this problem? Or downgrade the vitejs itself to v3.x?

**Comment by leejunhui** [comment]
> I am running into the same issue. Once I downgrade it to v3, the issue would be gone.

I tried to downgrade the vite-plugin-react to v3, but the error still exists

**Comment by LaurenceHo** [comment]
> @LaurenceHo Hi, are you just downgrade the vite-plugin-react to v3 to solve this problem? Or downgrade the vitejs itself to v3.x?

As far as I remember I only downgraded this to 3.1.0 and didn't downgrade vitejs.😅

**Comment by leejunhui** [comment]
> > @LaurenceHo Hi, are you just downgrade the vite-plugin-react to v3 to solve this problem? Or downgrade the vitejs itself to v3.x?
> 
> As far as I remember I only downgraded this to 3.1.0 and didn't downgrade vitejs.😅

That's interesting, I also downgraded vite-plugin-react to the 3.1.0, but the result is the same.

This is part of my package.json, maybe it's other plugin which could make the issue happen?
```json
 {
   "vite": "4.3.9",
    "@vitejs/plugin-react": "3.1.0",
    "vite-plugin-top-level-await": "1.3.0",
    "vite-plugin-wasm": "3.2.2",
    "vite-require": "0.2.3",
    "vite-plugin-rewrite-all": "1.0.1",
    "vite-plugin-svgr": "3.2.0",
    "vite-plugin-babel": "1.1.3",
    "@rollup/plugin-babel": "6.0.3"
}
```

**Comment by LaurenceHo** [comment]
> > > @LaurenceHo Hi, are you just downgrade the vite-plugin-react to v3 to solve this problem? Or downgrade the vitejs itself to v3.x?
> > 
> > As far as I remember I only downgraded this to 3.1.0 and didn't downgrade vitejs.😅
> 
> That's interesting, I also downgraded vite-plugin-react to the 3.1.0, but the result is the same.
> 
> This is part of my package.json, maybe it's other plugin which could make the issue happen?
> ```json
>  {
>    "vite": "4.3.9",
>     "@vitejs/plugin-react": "3.1.0",
>     "vite-plugin-top-level-await": "1.3.0",
>     "vite-plugin-wasm": "3.2.2",
>     "vite-require": "0.2.3",
>     "vite-plugin-rewrite-all": "1.0.1",
>     "vite-plugin-svgr": "3.2.0",
>     "vite-plugin-babel": "1.1.3",
>     "@rollup/plugin-babel": "6.0.3"
> }
> ```

Only vite and vite plugin react from above list are being used in my project.

**Comment by leejunhui** [comment]
> > > > @LaurenceHo Hi, are you just downgrade the vite-plugin-react to v3 to solve this problem? Or downgrade the vitejs itself to v3.x?
> > > 
> > > 
> > > As far as I remember I only downgraded this to 3.1.0 and didn't downgrade vitejs.😅
> > 
> > 
> > That's interesting, I also downgraded vite-plugin-react to the 3.1.0, but the result is the same.
> > This is part of my package.json, maybe it's other plugin which could make the issue happen?
> > ```json
> >  {
> >    "vite": "4.3.9",
> >     "@vitejs/plugin-react": "3.1.0",
> >     "vite-plugin-top-level-await": "1.3.0",
> >     "vite-plugin-wasm": "3.2.2",
> >     "vite-require": "0.2.3",
> >     "vite-plugin-rewrite-all": "1.0.1",
> >     "vite-plugin-svgr": "3.2.0",
> >     "vite-plugin-babel": "1.1.3",
> >     "@rollup/plugin-babel": "6.0.3"
> > }
> > ```
> 
> Only vite and vite plugin react from above list are being used in my project.

Well, it looks like the issue reached a dead end again. 😅

**Comment by ArnaudBarre** [comment]
Hi, the issue is that `vite-sample` is bundled by the deps optimiser and it seems that the default configuration for esbuild is to use React.createElement.

There is two solutions: 
- Remove the module from the optimizer:
```ts
  optimizeDeps: {
    exclude: ["vite-sample"],
  }
```
- Configure esbuild to use new jsx transformation:
```ts
  optimizeDeps: {
    esbuildOptions: {
      jsx: "automatic",
    }
  }
```

Maybe the default could be changed in Vite v5 as jsx runtime is now the default for most application (and in Vite plugins), but for now this is working as expected

**Comment by leejunhui** [comment]
@ArnaudBarre Hi, the second solution is worked.Thanks a lot~
