### ISSUE TITLE
When building micro frontend with library @originjs/vite-plugin-federation, multiple instance of react and react-dom is fetched

### ISSUE THREAD

**Issue by AsuraKev** [vitejs/vite-plugin-react#196]
### Describe the bug

I have the following setup with module federation, however it suppose to load react and react-dom dependency as singleton but its not doing that at the moment. Not sure if it has something to do with vite-plugin-react latest version or not.
![image](https://github.com/vitejs/vite-plugin-react/assets/52765572/aa4aee95-6471-4cec-9194-de80f9d97e19)

### Reproduction

none

### System Info

```shell
react 18.2.0 , @vitejs/plugin-react": "^4.0.3 @originjs/vite-plugin-federation": "1.2.3
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Sorry I'm not familiar with the `@originjs/vite-plugin-federation`.
I will need more precise information on what behaviour the plugin is currently doing that blocks your usecase to investigate.
