### ISSUE TITLE
I can't migrate from CRA to vite.

### ISSUE THREAD

**Issue by Apu-Emdad** [vitejs/vite-plugin-react#205]
### Describe the bug

I am trying to migrate from CRA to Vite.

- I cloned the project from GitHub
- I removed 'react-scripts' from both 'scripts' and 'dependencies' section from package.json
- I ran this command: ```yarn add vite @vitejs/plugin-react-refresh vite-plugin-svgr```
- I added **vite.config.js** to the root directory.

**vite.config.js**

```
import { defineConfig } from "vite";
import reactRefresh from "@vitejs/plugin-react";
import svgrPlugin from "vite-plugin-svgr";

export default defineConfig({
  build: {
    outDir: "build",
  },
  plugins: [
    reactRefresh(),
    svgrPlugin({
      svgrOptions: {
        icon: true,
      },
    }),
  ],
});
```

- I installed all the dependencies using the command: ```yarn```
- I moved the **index.html** to the root directory.
- I changed the **index.html** file. Now, It looks like this:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="/logo192.png" />
    <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
    <link rel="manifest" href="/manifest.json" />

    <!-- bootstrap css  -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- bootstrap js  -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <script type="module" src="/src/main.jsx"></script>

    <title>React App</title>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root">
      <script type="module" src="/src/index.jsx"></script>
    </div>
  </body>
</html>
```

- I renamed the **index.jsx** to **main.jsx**
- I made sure all the functional component has **.jsx** extension to their file name
- Finally i renamed the .env secret to ```VITE_STRIPE``` from **REACT_APP_STRIPE**

Then I ran this command: ```yarn start```
But it shows:

> vite start
> Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
>
> VITE v4.4.9  ready in 401 ms
>
> Local:   http://localhost:5173/
> Network: use --host to expose
> press h to show help

In http://localhost:5173/:
*This localhost page can’t be found*

You can see the code structure in [`GitHub`](https://github.com/Apu-Emdad/E-Mart-Client) at the commit: `vite integration failed` in `vite-integration` branch.

I would like to know what I did wrong and How can I successfully migrate from CRA to vite?

I tried

1. `yarn cache clean`

2.  `yarn vite dev` . returns:

   > yarn run v1.22.19
   >
   > $ C:\\Apu\\personal_project\\E-Mart-Client-vite\\E-Mart-Client\\node_modules\\.bin\\vite dev
   >
   > failed to load config from C:\\Apu\\personal_project\\E-Mart-Client-vite\\E-Mart-Client\\vite.config.js
   >
   > error when starting dev server:
   >
   > Error: Cannot find module '@vitejs/plugin-react'

3. `yarn add @vitejs/plugin-react-refresh`  again.

4.  `yarn vite dev`  returns the same as number **2.**

5. The issue persists. 

### Reproduction

https://github.com/Apu-Emdad/E-Mart-Client

### Steps to reproduce

checkout to the branch ```vite-integration```
switch to the commit ```vite integration failed```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 998.85 MB / 7.77 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.11 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Few things are off:
- @vitejs/plugin-react-refresh is in your dev deps intead of @vitejs/plugin-react
- the script tag in index.html should be outside of the root div (at the bottom)
- the entry point seems to be main.jsx in your commit and not index.js

**Comment by Apu-Emdad** [comment]
@ArnaudBarre  Firstly Thanks for your kind response. Sorry, I just forgot to push the latest changes. 

-  removed @vitejs/plugin-react-refresh 
- added @vitejs/plugin-react as dev dependency
-  fixed the index.html

The problem still persists. Can you please check the latest commit in the branch ```vite-integration```

**Comment by ArnaudBarre** [comment]
Two remaning changes:
```html
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
```
```js
// const KEY = process.env.REACT_APP_STRIPE; ->
const KEY = import.meta.VITE_STRIPE;
```
