### ISSUE TITLE
Can we provide a configuration that removes the prompt by "Could not Fast Refresh"? This is annoying.

### ISSUE THREAD

**Issue by llyp618** [vitejs/vite-plugin-react#208]
### Description

About "#consistent-components-exports", exporting constant or something in TSX or JSX files is a very common scene. I know that this will cause react refresh abnormality, but I may not want to see this annoying Warning

### Suggested solution

provide a configuration that removes the prompt: `react({ refreshWarning: false})`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
hot.invalidate that invalidate HMR is builtin in core as a warning. And I don't really want for people to be easy to mess up with HMR and then get the sensation that Vite has bad HMR. If you don't care about this, I see two options for you:
- Don't use this plugin and let esbuild handles everything. This will cause full-reload for every JS change
- Provide a custom logger in the Vite config and use the fallback handler for everything expect the "annoying" warning
