### ISSUE TITLE
Get preamble inside a new plug-in

### ISSUE THREAD

**Issue by webJose** [vitejs/vite-plugin-react#210]
### Description

Hello!  I wrote a Vite plug-in for `single-spa` and got in trouble loading a React micro-frontend into a page that was rendered by a Vite + Vue project.  I don't know much about the "preamble", but seems to be a required piece of code for HMR, and I saw in the code in this repository that this preamble is added by this plug-in.

Since the vue plug-in for Vite doesn't seem to add this preamble, again because it seems to be a React-only thing, the resulting webpage doesn't have the required preamble for the micro-frontend in React to work with HMR.  I had to disable HMR to get the `single-spa` scenario work.

### Suggested solution

So, my enhancement request would be:  Create a plug-in whose sole purpose is to add the preamble.  Then this plug-in and my plug-in (`vite-plugin-single-spa`) can both use it to get HMR, regardless of which other plug-in builds the index page.

### Alternative

The alternative I see would be for me to steal the preamble code I find here and add it to my plug-in.  This will create a copy of a piece of code I don't know how to maintain.

### Additional context

I stumbled upon this problem while writing [this article](https://webjose.hashnode.dev/vite-plugin-single-spa-vite-projects-made-single-spa-compatible-with-one-plug-in).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
What is blocking you from adding the react plugin to your vite config so it injects the preamble?

**Comment by webJose** [comment]
The fact that the project is not React?  The project is Vue.

**Comment by ArnaudBarre** [comment]
But the project is using React component?

**Comment by webJose** [comment]
Yes, as a `single-spa` component.  I believe that adding the React plug-in in the pipeline to process an all-vue code is not correct.

Just so we are clear:  The React component is **not** part of the source code that is being compiled.  It is an entirely separate project.  The project that produces the index page is 100% Vue.  The React component is nowhere near this project when it is compiled.

**Comment by ArnaudBarre** [comment]
If the project contains only .vue and .TS files, the plugin will not process anything and just inject the preamble and the runtime code for HMR. You can also inject it only for dev. But HMR could be buggy depending on the setup.
I don't really understand the setup and what you're trying to achieve, Vite has no official support for micro-frontend and splitting this plugin in two is clearly not a move in that direction.

**Comment by webJose** [comment]
Thanks for the tip.  I don't know what kind of processing is done by the plug-in, but you are confident that it won't affect the result.  That is encouraging for sure, but my concern is:  Will that continue to be true over time?  This is the reason I would like to see preamble injection handled by a separate plug-in:  Just adding the React plug-in complete feels like walking on thin ice.

Just in case it is helpful, I'll try to explain the set-up:

`single-spa` is a library that provides a standardized module-loading process.  The loaded modules follow a predefined type, which basically defines 3 functions:  `bootstrap`, `mount` and `unmount`.  Besides satisfying the function signatures, nothing else is imposed over the imported module.

So my plug-in, `vite-plugin-single-spa`, helps developers achieve exportation of said module.  There are other packages provided by the `single-spa` team and community that help developers easily create the aforementioned functions, called the lifecycle functions.

The main part of this process is:  `Index.html` for a micro-frontend project ceases to be the input file to rollup, and my plug-in exchanges it for a file that exports the lifecycle functions.

This last part is what is breaking HMR for the resulting React, `single-spa`-compliant module:  The preamble goes into `index.html`, something that has been discarded in favor of a different module.

I realize that Vite has no official support for micro-frontends, and I am not really asking for that.  My plug-in is the one that intends to give Vite this support.  I'm simply asking for something I think is 100% neutral that doesn't break anything:  Let's get preamble injection in its own plug-in.  Then any plug-in that needs it (so far, this plug-in and my plug-in) can confidently inject it without risking walking on thin ice.  I will always be assured that the plug-in's purpose will not change over time, and that it guarantees that other files won't be affected.

Thanks for the time!  Hopefully your team can have a look at this request and respond favorably.  Have a good day!

**Comment by webJose** [comment]
Hello again.  It seems I am not the only one that has had the need to get the preamble in a non-React project.  Have a look at this [source code](https://github.com/MilanKovacic/single-spa-vite/blob/main/root-config/index.html).

The need is real! :smile:

**Comment by ArnaudBarre** [comment]
Started to look into the doc of single-spa, and wow that's a lot of complexity to avoid having a main app lazy loading part of the app that could use a different framework, and just adding a Vite plugin to support the new framework (I guess that's mainly because of Angular not compatible with Vite in the past).

I would really like to see a live setup on Stackblitz of the plugin you're working on + a Vue app + a React app that cause the preamble issue so that I can better investigate this HMR issue. Because I really feel that once the preamble will be loaded, HMR won't work because of not being on the same host.

**Comment by webJose** [comment]
Hi!  Thank you very much for your interest and willingness to have a look.

I don't know how to create a live Stackblitz demo that includes 2 projects running simultaneously and able to communicate with each other the way `single-spa` requires, so I created a Github repo:  https://github.com/webJose/singleSpaHMRIssue

It contains a Vue and a React project.  The Vue project is the root project; the React project is the micro-frontend project.

This may be run in a single VS Code window.  Open the project, then open two consoles.  Run `npm run dev` in each console for each project.  Then open the root's webpage.  The Vue project will be shown.  Now open the browser console and click the link **Load SPA01**.  This will trigger the loading of the React micro-frontend and you'll see the preamble error in the browser console.

As stated originally, the problem happens because the index page was produced by the root project, a 100% Vue project.

Let me know if I can help further.  For example, I can set more projects up.  For instance, if you want to try with a React root, I can set it up for you.

**Comment by ArnaudBarre** [comment]
So yeah that kind of setup doesn't work in Vite. Even by adding the react plugin the root project, you then have issues asset loading and HMR is still broken because the updates to the side apps are only pushed to clients connected via WS to the side dev-server.

Here is an example of putting everything into one Vite project: https://stackblitz.com/edit/vitejs-vite-xmeppk?file=react-app%2FGlobalRouter.tsx (This is clearly buggy because the Vue app mount into the same root as React which breaks the routing).

Then dev, HMR, build, preview, code splitting (including CSS), lazy loading works without anything special.

**Comment by webJose** [comment]
> So yeah that kind of setup doesn't work in Vite. Even by adding the react plugin the root project, you then have issues asset loading and HMR is still broken because the updates to the side apps are only pushed to clients connected via WS to the side dev-server.

I saw in that other link from other repo I found, that the preamble seems to need the host name.  I did not think much of that, to be honest, but I imagine is what is needed to make the WS connection, as you say.  Makes sense.

Question:  What if the hypothetical new plug-in received this host name through its options?

```ts
vitePluginReactPreamble({ host: 'localhost:4101' })
```

Would that be sufficient for the WS connection to be established successfully?  The example assumes that port 4101 is the React micro-frontend Vite server, which is running the React plug-in.  The sample code above would be in my plug-in's configuration in the **other** project (in the example, the Vue project).

**Comment by ArnaudBarre** [comment]
The WS connection is something from Vite core, not this plugin. The good thing about the core dev client is that the host can be explicit. So maybe you can start to see if you're single-spa plugin can inject a import of the other dev client on the main html and see if it works. Then maybe we can see how to make this possible for the react plugin. I still don't think it should be extracted. And it hasen't change in years and is hardcoded in various other framework (Vite-ruby, laravel ruby) so I will probably not break it.


But before you spent more time on this, really think twice about all this setup and why putting everything in the same Vite project is an issue. With the `fs.allow` config, you can even import source code outside of the main vite config root.

**Comment by webJose** [comment]
I believe this happens already.  Whenever I run this setup, I always see 2 of "Vite connecting" and "Vite connected" messages (4 in total).

**Comment by ArnaudBarre** [comment]
I've look at it and I see only one log. I'm closing this because clearly what you want need to be addressed in core (if it is, personally given the current possibilities for Vite, the kind a feature request is Conway law at work). There is probably ongoing discussions for this kind a support, and maybe some core team member could work on it in the future, but this is not the current priority
