### ISSUE TITLE
Could not find a declaration file for module '@babel/core'.

### ISSUE THREAD

**Issue by saramorillon** [vitejs/vite-plugin-react#211]
### Describe the bug

When using `@vitejs/plugin-react`@4.0.4, I get this error when building my application:
![image](https://github.com/vitejs/vite-plugin-react/assets/4224278/931cd720-7c30-4703-868e-f8d2af16c465)

I can get rid of this error by installing `@types/babel__core`, but I don't think it should be the user's responsibility to install a type on which a dependency depends.

### Reproduction

https://github.com/saramorillon/inventory/tree/b612b372734dda6454872427a76b037050d50ed9

### Steps to reproduce

In `front` directory, run `yarn install` followed by `yarn build`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 6.41 GB / 15.93 GB
  Binaries:
    Node: 19.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.96
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

yarn

### Logs

node_modules/@vitejs/plugin-react/dist/index.d.ts:1:49 - error TS7016: Could not find a declaration file for module '@babel/core'. '/node_modules/@babel/core/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/babel__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@babel/core';`

1 import { TransformOptions, ParserOptions } from '@babel/core';
                                                  ~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This is because you don't have `skipLibCheck` enabled in your tsconfig. This is very common and given that the first time it's been reported since the repo was split 7 months ago, this is even more common than I would expect.
Nonetheless maybe there is some usage of the plugin in `vite.config.ts` that is badly typed. I will look into it.

Checking lib types can help find issues in the libs you use but most of the time this is unactionable and this is why most template enable this TS flag.

**Comment by saramorillon** [comment]
I would rather not enable `skipLibCheck` is my tsconfig as it helps me find inconsistencies with the versions of the libs I use (e.g. if I end up with two different version of `@types/react` in my yarn.lock).
I'm looking forward the result of your investigations, thank you.
