### ISSUE TITLE
Unmet peer dependency with Vite 5

### ISSUE THREAD

**Issue by IanVS** [vitejs/vite-plugin-react#218]
### Describe the bug

I'm trying out the vite 5 beta, and am getting a warning from pnpm:

```
├─┬ @vitejs/plugin-react 4.0.4
│ └── ✕ unmet peer vite@^4.2.0: found 5.0.0-beta.1
```

Can vite 5 just be added to the `peerDependencies`?

### Reproduction

N/A

### Steps to reproduce

Create a vite react project, update vite to 5 beta, install with pnpm.

### System Info

```shell
`sh: envinfo: command not found`
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
For me this warning is fine when testing beta version of Vite. And I can't say for sure the plugin will be compatible with the next beta patches or the next major, a small breaking change can still be introduced I think

**Comment by MikeMcC399** [comment]
[vite](https://www.npmjs.com/package/vite) `5.0.0` has now been released (no longer beta or release candidate)
