### ISSUE TITLE
@vitejs/plugin-react can support more extensions 

### ISSUE THREAD

**Issue by LaamGinghong** [vitejs/vite-plugin-react#22]
### Clear and concise description of the problem

I'm doing markdown conversion to React component. However, this plugin may only be supported `.jsx?` or `.tsx?` file. So I had to use an extra Babel plugin to handle the files generated by the markdown transformation.

### Suggested solution

Add a configuration extension to the plugin's options and support any text that conforms to React component.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Niputi** [comment]
please give more details.
what exactly are you trying to do and how do you expect it to work

**Comment by LaamGinghong** [comment]
@Niputi 
I wrote a Vite plugin to transform markdown to React component. The output of the plugin looks something like this:
```jsx
export default () => <div> {/* The transformed code */}</div>
```
However, `@vitejs/plugin-react` could not accept a `.md` file and I had to use babel to transform the jsx to js.

This is my current configuration file:

```js
plugins: [
  vitePluginDocs(), // my markdown transform plugin
  babel({
    extensions: ['.md'],
    configFile: false,
    presets: [['@babel/preset-react', { runtime: 'automatic' }]],
    babelHelpers: 'bundled'
  })
  viteReact()
]
```

I want the `@vitejs/plugin-react` to accept an extra parameter to accept more file's format like this:

```js
plugins: [
  vitePluginDocs(), // my markdown transform plugin
  viteReact({ extensions: ['.tsx', '.md'], })
]
```

So I can remove the babel from my config.

**Comment by LaamGinghong** [comment]
By reading the plugin's code, I found that the plugin will only convert `mjs | js | jsx | ts | tsx` file

**Comment by bluwy** [comment]
`vite-plugin-svelte` has a similar feature too that allows [specifying the extensions](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#extensions). Probably worth nothing a caveat though: https://github.com/sveltejs/vite-plugin-svelte/issues/60

**Comment by LaamGinghong** [comment]
@bluwy I think it's a nice feature, so what do you think?

**Comment by bluwy** [comment]
I'm not familiar with React (nor the vite plugin) so I can't say for sure if there are caveats to this. @aleclarson might know more about it.

**Comment by ArnaudBarre** [comment]
Hi!
Yes that's a limitation of the current API. Making this change non breaking would make the API unusable so I plan to change this in the next major with #53, hopefully in less than one month
