### ISSUE TITLE
Importing from node_modules .tsx in dev

### ISSUE THREAD

**Issue by xixixao** [vitejs/vite-plugin-react#220]
### Describe the bug

Using `npm create vite@latest my-app -- --template react-ts`
importing from a tsx file inside node_modules that uses `jsx: "preserve"` doesn't work.

Vite build works fine.

People who reported this before were pointed at this comment:
https://github.com/vitejs/vite-plugin-react/issues/192#issuecomment-1627384670

The first option, exclude, doesn't work:

> Uncaught SyntaxError: The requested module '/node_modules/attr-accept/dist/es/index.js?v=327b71f0' does not provide an export named 'default' (at index.js?v=327b71f0:29:8)

The second option works, but because it applies to all dependencies, it might break some (the ones that already import React).

It feels like this is broken somewhere between this plugin and esbuild. Rollup clearly doesn't have a problem.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ch4exl?file=src%2FApp.tsx

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: arm64 Apple M1
    Memory: 2.12 GB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/40518_1694570633741/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/40518_1694570633741/bin/npm
    pnpm: 8.7.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react: ^4.0.3 => 4.0.4
    vite: ^4.4.5 => 4.4.9
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
UploadButton.tsx:58 Uncaught ReferenceError: React is not defined
    at UploadButton (UploadButton.tsx:58:3)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I'm not sure the first option will brake anything. And I think only internal libs ship JSX to npm.

The error when excluding the lib is due to multiple things:
- When a lib is excluded, the code in node_mdoules will not behave like source code, and dependencies of this dependency will be loaded without pre-bundling/dep-optimization
- The attr-accept ships bad esm (https://github.com/react-dropzone/attr-accept/pull/64)
- Because Vite is serving it wihtout transpiler/bundler, this cannot be fixed (whereas esbuild is able to fix that un bundling) 

The solution for now is to re-include react-dropzone in the optimized deps:
```
  optimizeDeps: {
    exclude: ["@xixixao/uploadstuff/react"],
    include: ["react-dropzone"]
  }
```
 
But IMO using the first option is simpler in maintenance and if you use other internal/personal packages. And I just asked the team what they think about making this the default in Vite 5

**Comment by ArnaudBarre** [comment]
For info I will push a major version just after Vite 5 to change the default of `optimizeDeps.esbuildOptions.jsx` to `"automatic"` if not set by the user or another plugin and the jsx option is `"automatic"` (the current default). Keeping it open as a reminder
