### ISSUE TITLE
Babel and PostCSS polyfills are not working

### ISSUE THREAD

**Issue by SaroGFX** [vitejs/vite-plugin-react#221]
### Describe the bug

When migrating from Webpack to Vite, a lot of older browser versions crashed. I noticed that there are no polyfills. Even when configuring the target explicitly or adding presets. 

However, Vite and this plugin states that it should have this out of the box. Why is polyfill and and PostCSS not being applied? It also happens in the build version. 

### Reproduction

https://github.com/SaroGFX/polyfill-vite-test

### Steps to reproduce

1. Install React project with Vite
3. Add a modern JS such as `array.prototype.at()` or a private method
4. Test the build on a browser such as Safari 14 results in crash 

![Screenshot 2023-09-13 at 19 04 57](https://github.com/vitejs/vite-plugin-react/assets/3781800/6b279c68-9583-499c-8fe6-8c105f1adca6)

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 28.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.0.3 => 4.0.4 
    vite: ^4.4.5 => 4.4.9
```

###

Default config on install 
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  build: { target: "ES2022" },
});

```
### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Vite doesn't handle polyfills: https://vitejs.dev/guide/build.html#browser-compatibility

Personally I have a small custom polyfill for some new array method like `at`

Class private fields are down-transpiled by esbuild at build time (if you don't set build.target to es2022)
