### ISSUE TITLE
Types for plugins fails with Native ESM 

### ISSUE THREAD

**Issue by kentcdodds** [vitejs/vite-plugin-react#225]
### Describe the bug

```ts
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
	plugins: [
		react(), // <-- typescript error here
	],
})
```

The error is:

```
This expression is not callable.
  Type 'typeof import("/Users/kentcdodds/Desktop/vite-plugin-react-types-issue/node_modules/@vitejs/plugin-react/dist/index")' has no call signatures.
```

I have `"type": "module"` in the `package.json`.

### Reproduction

https://github.com/kentcdodds/vite-react-native-esm-typescript-issue

### Steps to reproduce

```
git clone https://github.com/kentcdodds/vite-react-native-esm-typescript-issue.git
cd vite-react-native-esm-typescript-issue
npm install
npm run typecheck
```

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 359.13 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 9.6.7 - ~/n/bin/npm
    pnpm: 7.25.0 - /opt/homebrew/bin/pnpm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 117.1.58.127
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    vite: ^4.4.9 => 4.4.9 
```
```


### Used Package Manager

npm

### Logs

Here's my output for the reproduction steps:

```
$ git clone https://github.com/kentcdodds/vite-react-native-esm-typescript-issue.git
cd vite-react-native-esm-typescript-issue
npm install
npm run typecheck
Cloning into 'vite-react-native-esm-typescript-issue'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (8/8), 11.17 KiB | 11.17 MiB/s, done.

added 67 packages in 630ms

> vite-native-esm-typescript-issue@1.0.0 typecheck
> tsc

vite.config.ts:5:12 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/kentcdodds/Desktop/vite-react-native-esm-typescript-issue/node_modules/@vitejs/plugin-react/dist/index")' has no call signatures.

5  plugins: [react()],
             ~~~~~


Found 1 error in vite.config.ts:5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Yeah this is because of `nodenext`. @bluwy knows this issue well. I think this should be solved with unbuild v2 (#213), I will take a look at it.

Using bundler works I think

**Comment by ArnaudBarre** [comment]
Ok I've merged #213, more .dts files are now generated.

Please don't use node16/nodenext as a resolution algorithm, it's just give you headache with all the legacy of node on top of adding absurd rules like re-mapping `.js` to `.ts` in imports.
bundler + allowTSImports is the way to go

**Comment by kentcdodds** [comment]
Thank you!

But what if the code I'm writing isn't bundled?

**Comment by ArnaudBarre** [comment]
it depends:
- Writing TS:
  - If the runtime support TS natively, you should not have to worry about all these node restrictions (Bun <3)
  - If not, you need to at least transpile and in that case it doesn't cost to add a bundler. For me this is the role of the bundler to take care of cjs/esm compat depending on your target, your source code and your libs. And having a bundler doesn't mean you have one output. But most of the time it leads to smaller output and faster loads to do some bundling
- Writing JS with JS docs: Personally not a fan but might be the only case where it makes sense if your lib is node only

**Comment by bluwy** [comment]
Just checked the new output after the PR. LGTM!
