### ISSUE TITLE
Make plugin-transform-react-jsx-self and plugin-transform-react-jsx-source optional

### ISSUE THREAD

**Issue by onurhb** [vitejs/vite-plugin-react#228]
### Description

I am trying to run a simple vitest test with custom jsx. `plugin-transform-react-jsx-self` adds circular references which makes the element not serialiable (adds attribute: `__self`). You can try to run this test: https://github.com/onurhb/slate-immer-error/blob/minimal/src/editor.test.tsx.

I need to omit this plugin as I am not able to test using `slate-hyperscript`. See example here: https://github.com/ianstormtaylor/slate/blob/main/packages/slate-hyperscript/test/fixtures/cursor-element-nested-end.tsx

Slate uses Immer under the hood which does not allow circular references. 

### Suggested solution

Make `plugin-transform-react-jsx-self` and `plugin-transform-react-jsx-source` optional. Let us disable these with config.

### Alternative

I have to remove `__self` in my code manually. I want instead to be able to disable these plugins. 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [ ] Read the [docs](https://vitejs.dev/guide).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sapphi-red** [comment]
If you don't need HMR features for React, then you don't need plugin-react. Vite supports JSX out-of-the-box.

**Comment by ArnaudBarre** [comment]
Yeah probably you can skip completely the plugin in test env. Also these plugins are not injected when using the classic runtime which maybe fix the issue?
The need for using this plugin while using classic runtime and without the babel JSX plugins need to be more motivated
