### ISSUE TITLE
[@vitejs/plugin-react] VS Code Breakpoints do not get hit after first fast refresh in plugin-react in new project

### ISSUE THREAD

**Issue by sevenfields-matt** [vitejs/vite-plugin-react#23]
### Describe the bug

After creating a brand new Vite project using create-vite(yarn create vite) breakpoints in VS Code do not get hit after the first change and refresh.

Refresh meaning the fast HMR refresh.  The app refreshes well in the browser but it leaves the VS Code debugger in an unusable state.  

Refreshing the browser, or refresh through VS Code allows breakpoints until the next refresh.

### Reproduction

Reproduce:

1. Create a react-ts vite project using yarn create vite
2. run yarn dev
3. Inside of VS Code create the following launch.json:
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Chrome",
			"request": "launch",
			"type": "pwa-chrome",
			"url": "http://localhost:3000",
			"webRoot": "${workspaceFolder}"
		}
	]
}
```
4. Place a breakpoint on 
```
  const [count, setCount] = useState(0)
```
5. Debug the app in vs code
6.  Notice your breakpoint is hit
7. Change the line "Hello Vite + React" to "Test breakpoint" and save
8. Notice the app has successfully updated in the browser
9. Notice that your breakpoint is not hit
10. Refresh the page and notice your breakpoint is now hit

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 3600XT 6-Core Processor

    Memory: 2.59 GB / 15.91 GB
  Binaries:
    Node: 14.15.4 - C:\apps\dev\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\apps\dev\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
    Internet Explorer: 11.0.19041.1202
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by m430** [comment]
me too, I can't debugging in chrome dev tool, It's a serious bug.

**Comment by connor4312** [comment]
This'll be fixed in the next [nightly release](https://github.com/microsoft/vscode-js-debug#nightly-extension) of the vscode js debugger. I don't think Vite needs to take any action here.

**Comment by ArnaudBarre** [comment]
Thanks a lot @qm965 for making an upstream issue and @connor4312 for the quick update!
