### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/prop-types/index.js?v=cf7fa801' does not provide an export named 'default

### ISSUE THREAD

**Issue by 322332** [vitejs/vite-plugin-react#239]
### Describe the bug

Hello, I have an npm library called platform. In this library, I have route structures and menus that I designed with my material UI library https://github.com/322332/platform. I want to install and use this library in other projects with npm, but when I add some material UI components, I get errors like ncaught SyntaxError: The requested module '/node_modules/prop-types/index.js?v=cf7fa801' does not provide an export named 'default' (at elementAcceptingRef.js?v=cf7fa801:1:8)

This error only comes in npm run dev.

npm run build and later
If I do npm run preview, I can build and use it without any problems.

### Reproduction

npm create vite-extra@latest

### System Info

```shell
windows 11, chrome
```

### Used Package Manager

npm

### Logs

vite

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
You're reproduction is incomplete. it doesn't have an index.html or vite config.
