### ISSUE TITLE
`@vitejs/plugin-react` processing excluded files

### ISSUE THREAD

**Issue by sibbng** [vitejs/vite-plugin-react#24]
### Describe the bug

`@vitejs/plugin-react` processing files that defined in `exclude` option.

```ts
export default defineConfig({
  plugins: [
    react({
      exclude: /App/,
    }),
  ],
});
```

I was expecting `@vitejs/plugin-react` to bypass processing matching files and throw an error but it's still processing those files.

`include` and `exclude` filters are only checked when loading react-refresh plugin and jsx transforms are still processes for all jsx files:
https://github.com/vitejs/vite/blob/e8c840abd2767445a5e49bab6540a66b941d7239/packages/plugin-react/src/index.ts#L170

In my opinion we should do that on top of transform function by adding this:
```ts
async transform(code, id, options) {
  if (!filter(id)) {
    return
  }
  // ...  
```

#### **Why I do this?**
I'm currently using Solid and React on same project and both of them have their own jsx transform. I need to prevent them processing the same file. I have naming convention in my app `.react.tsx` for React components and `.solid.tsx` for Solid components. I didn't include Solid in my repro because vite-plugin-solid [doesn't have an option to exclude files](https://github.com/solidjs/vite-plugin-solid/blob/b57f3e9ed8c3048afe7d1f33bb85b4daefad2e03/src/index.ts#L308) but I patched their plugin locally and will make a feature request on their repo. 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-k286cf?file=vite.config.js&terminal=dev

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/core instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Mnigos** [comment]
I got same issue. I described that `*.stories.tsx` files should b excluded, but vite is still trying to build those files.

**Comment by ArnaudBarre** [comment]
> vite is still trying to build those files

I think your source code should not import code form stories.

Anyway the exclude filter today is not good and not enough, I should get back on working on the linked PR this week or next week and publish a 4.0-beta version shortly after
