### ISSUE TITLE
HMR Invalidate when exporting custom hooks

### ISSUE THREAD

**Issue by Strahinja-Samardzija** [vitejs/vite-plugin-react#243]
### Describe the bug

When I export a custom hook, I get "hmr invalidate. Could not Fast Refresh." message. Even though it does update the page.
When I name the hook with capital Use the message is gone.

If this is not a bug I hope someone can put the solution in Readme section: https://github.com/vitejs/vite-plugin-react-swc#consistent-components-exports.

I'm using Vite JavaScript+React+SWC template.

Here is the minimal reproducible example:

```import React, { useState } from "react";
import ReactDOM from "react-dom/client";

const useHook = () => {
	const [first, setFirst] = useState("second");
	return 1;
};

ReactDOM.createRoot(document.getElementById("root")).render(
	<React.StrictMode>
		<p>Welcome</p>
	</React.StrictMode>
);

export default useHook;
```

### Reproduction

https://github.com/vitejs/vite-plugin-react/issues/new?assignees=&labels=pending+triage&projects=&template=bug_report.yml

### Steps to reproduce

npm create vite@latest
react+javascript+SWC template
cd vite-project
npm install

paste this to src/main.jsx

```import React, { useState } from "react";
import ReactDOM from "react-dom/client";

const useHook = () => {
	const [first, setFirst] = useState("second");
	return 1;
};

ReactDOM.createRoot(document.getElementById("root")).render(
	<React.StrictMode>
		<p>Welcome</p>
	</React.StrictMode>
);

export default useHook;
```
save src/main.jsx
npm run dev
open page in browser
save src/main.jsx again and maybe try more than 5 times if it does not show up immediately

### System Info

```shell
windows,
npmPackages:
    @vitejs/plugin-react-swc: ^3.4.0 => 3.4.0
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Exporting a hook from the enrtypoint doesn't make a lot a of sense. But propbably you're doing that with other components, in that case you should put the hooks and components in separate files

**Comment by Strahinja-Samardzija** [comment]
Thank You.

After changing the file extension from .jsx to .js for the files with hooks, the error has disappeared. 

I believe it would be beneficial to add this information to the Readme and to mention that exported hooks should be placed in separate files.
