### ISSUE TITLE
Babel reformats the input file, causing source references to be wrong

### ISSUE THREAD

**Issue by Artur-** [vitejs/vite-plugin-react#266]
### Describe the bug

Using this file
```
import { TextField } from '@hilla/react-components/TextField.js';

export default function HelloWorldView() {
  return (
    <>
      <section>
        <TextField
          label="first"
/>
<TextField
          label="second"
        />
      </section>
    </>
  );
}
```
the source info for the first text field is correctly line 7, column 9
however, for the second text field it is line 10 (correct) but column 9 when it should be column 1

The code is fine before it is passed to babel but logging it after `const result = await babel2.transformAsync(code, {` shows it has changed to
```
import { TextField } from '@hilla/react-components/TextField.js';

export default function HelloWorldView() {
  return (
    <>
      <section>
        <TextField
          label="first" />

        <TextField
          label="asdf" />

      </section>
    </>);

}_c = HelloWorldView;var _c;$RefreshReg$(_c, "HelloWorldView");
```

### Reproduction

See above

### Steps to reproduce

See above

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.17 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 107.1.45.123
    Chrome: 119.0.6045.159
    Chrome Canary: 121.0.6147.0
    Edge: 119.0.2151.72
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react: 4.2.0 => 4.2.0 
    vite: 5.0.2 => 5.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
In which context "source references are wrong"? Babel provide source maps as an output that that passed down to Vite and esbuild I think so source maps should be correct I think. Maybe the column is wrong in the source map output, is this that?

**Comment by Artur-** [comment]
I am looking at the source info written in the output JS and available in the browser

**Comment by Artur-** [comment]
My understanding is that the input file goes through babel, babel slightly changes the formatting and then the reformatted file goes through esbuild, which uses `jsx-dev-runtime` and adds the source references to the JS. Now when an element does not start in the same place in the babel processed file and in the original source file, these references are wrong. Like for  the second text field in the example above

**Comment by Artur-** [comment]
I tested this outside the plugin to confirm how it works. With `.babelrc` 
```
{
  "sourceMaps": true,
  "generatorOpts": { "decoratorsBeforeExport": true },
  "parserOpts": {
    "plugins": ["jsx", "typescript"],
    "sourceType": "module",
    "allowAwaitOutsideFunction": true
  },
  "retainLines": true
}
```
running `npx babel  index.tsx` 

produces
```
import { TextField } from '@hilla/react-components/TextField.js';

export default function HelloWorldView() {
  return (
    <>
      <section>
        <TextField
          label="first" />

        <TextField
          label="second" />

      </section>
    </>);

}
```

Now the second text field no longer starts at the same location so if esbuild later on adds the source references, they will be wrong.

If I instead include the jsx plugins in the babel run: `@babel/plugin-transform-react-jsx-self` and `@babel/plugin-transform-react-jsx-source`

then I get the expected source references, probably as it uses the original file for those:
```
var _jsxFileName = "/.../index.tsx";import { TextField } from '@hilla/react-components/TextField.js';

export default function HelloWorldView() {
  return (
    <>
      <section __self={this} __source={{ fileName: _jsxFileName, lineNumber: 6, columnNumber: 7 }}>
        <TextField
          label="first" __self={this} __source={{ fileName: _jsxFileName, lineNumber: 7, columnNumber: 9 }} />

        <TextField
          label="second" __self={this} __source={{ fileName: _jsxFileName, lineNumber: 10, columnNumber: 1 }} />

      </section>
    </>);

}

**Comment by Artur-** [comment]
So if I modify this plugin and use the babel jsx plugins also for non classic mode, then the info looks correct but it all fails because esbuild apparently adds another set of __self and __source attributes

**Comment by Artur-** [comment]
Seems like vite-plugin-react-swc does the same as this plugin but does not show the same bug. What's the relationship between the two plugins?

**Comment by ArnaudBarre** [comment]
Ok I see the issue and I will close this a will not fix. Correct columns index in dev is not worth the cost of transpiling JSX via Babel, and most of the time people will input formatted code.

If this is something important for you, you should make sure fast-refresh and JSX are handled at the same time, either by switching to the SWC plugin or by configuring the Babel one to do so (but in my benchmark it was slowing tansformation by ~30%). If you also to TS transpilation, then you can disable esbuild in dev (like the swc plugin).

For a short description of both plugins, see https://vitejs.dev/plugins/#vitejs-plugin-react

Edit: clicked the wrong close button

**Comment by Artur-** [comment]
Thanks, I agree that for most users the exact start of an element makes no difference... but some cases are different :)

I'll look into if we can switch to the swc plugin
