### ISSUE TITLE
Decorators not working with React class components

### ISSUE THREAD

**Issue by albert-schilling** [vitejs/vite-plugin-react#268]
### Describe the bug

We currently try to migrate our React application from Webpack to Vite. 
Unfortunately, this does not seem to be possible without major code changes because decorators are not properly transformed by Babel and do not point `this` to the class component as expected.
We tried many variations of `parserOptions` (`decorators`, `decorators-legacy`) in the Babel settings in the `vite.config.ts` without success.

See this minimal reproduction: https://codesandbox.io/p/devbox/vite-react-inversify-3h6rjq

Exemplary code snippets:
```
export default class App extends React.Component {
  @logProperty
  someProp: string = "someValue";

  constructor(props: any) {
    super(props);
  }

  render() {
    return <div>Hello from the class component.</div>;
  }
}

export function logProperty(target: any, key: string) {
  // `This` should be defined
  // and reference the React class component that uses the decorator.
  !this && throw new Error("This in decorator is undefined!");

}
```

### Reproduction

https://codesandbox.io/p/devbox/vite-react-inversify-3h6rjq

### Steps to reproduce

Seehttps://codesandbox.io/p/devbox/vite-react-inversify-3h6rjq

### System Info

```shell
None special, see Codesandbox
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi, I don't have insights for now on this, I never used decorators and don't really want to spend 30' understanding the various difference between all the differents spec of decorators. I sorry for you that so much framework choose to use them despite the unspec nature of it.

**Comment by albert-schilling** [comment]
Thank you for the response Arnaud. We will stick to Webpack/Babel for now until decorators become a native language feature (and implemented by esbuild).
