### ISSUE TITLE
React hooks reran on every edit

### ISSUE THREAD

**Issue by jasekiw** [vitejs/vite-plugin-react#271]
### Describe the bug

All my hooks are reran on any edit in my codebase. create-react-app did not have this issue so I wonder if there is an issue with integrated react-refresh with vite or it is somehow intentional.

This is causing a lot of issues with my development experience as my local state is wiped from a useEffect in many cases. 
Please read the readme from the example project to demonstrate the re-running of hooks.
https://github.com/jasekiw/vite-react-hooks-issue#readme

It would make sense to rerun the hook if the code inside the hook was changed. However since they rerun on every edit, it is a real nuisance.

### Reproduction

https://github.com/jasekiw/vite-react-hooks-issue

### Steps to reproduce

git clone https://github.com/jasekiw/vite-react-hooks-issue
cd vite-react-hooks-issue
1. run `yarn install`
2. run `yarn run dev`
3. Open Developer console, there should be two logs of "useEffect: 0" since strictmode is enabled.
4. Go to src\App.tsx and edit "Vite + React" to any other text ex. "Vite + React + Typescript"
5. Check the console again and there is a 3rd log of "useEffect: 0"

### System Info

```shell
System:
    OS: Windows 11 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 17.12 GB / 63.73 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.1
    vite: ^5.0.0 => 5.0.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This is intended, I'm surprised this was not the case with CRA.
See https://nextjs.org/docs/architecture/fast-refresh#fast-refresh-and-hooks
I work with that for years now and I don't have issue with that. As said in the next docs, having your hooks runs one extra time in dev should not be an issue

**Comment by jasekiw** [comment]
@ArnaudBarre

Even though this is marked as complete I would be grateful for a little more discussion about this.

A couple of thoughts:

I am weary about mentioning next here as this is not related to next. They use their own architecture that is harder to migrate to which is why I chose vite (coming from CRA). I would expect a link to the following document instead [useEffect](https://react.dev/reference/react/useEffect), however I can't find anything in there referring to what is said in the next document other than strict mode. StrictMode does not cause the inconvenience that I am referring to here.  It is the "seemly random" running of the hook that seems to inconvenience development. I say seemly random because they do not happen in succession but rather when the developer makes a change.

Is it causing a issue? No. Is it inconvenient? yes. For a  better development experience I had to check the dependencies myself. Is it okay to ask developers to have to wright additional application code to check dependencies just so the fast refresh is more convenient? I'm not implying an answer rather, just asking the question.

Next seems to imply yes however I would love a deeper explanation of this from somewhere.
> However, writing code resilient to occasional re-running of useEffect is a good practice even without Fast Refresh. It will make it easier for you to introduce new dependencies to it later on and it's enforced by [React Strict Mode](https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode), which we highly recommend enabling.

A little bit of background: my app uses react-router which does not unmount and remount the component on navigation which is why I had to write a useEffect with a dependency on the current url to fetch data but I'm sure there are many other instances where this would crop up. In some cases I could see that being desirable. In my case it's a very large form so I will be making many changes to. It is very inconvenient to have the current component I am working on disappear because the form is reset via the request to the backend. Maybe the ok route is to just check dependencies in application code to prevent the fetch from wiping out form state.


I would like to ask what is the reasoning for rerunning all hooks vs only the ones that have changed? Is it just too much complexity to detect what code was changed and only re-run the changed hooks?  Or is it because only running the hooks that have changed would not cover all the cases?

Thanks for your time!

**Comment by ArnaudBarre** [comment]
Yeah the ecosystem is missing some docs about Fast Refresh, it was initially on the RN docs, then Gatsby improved a bit on it and now it seems that Next have done some addition. This is on my todo list to create a in depth official page for that on react.dev, but there are a lot of others things I want to do. Anyway, the runtime is the same for all frameworks, so most of the rules don't change depending on if it runs in Next or Vite and for this one this is part of the shared runtime.

In your case I think there are few things that feel odd:
- Missing client cache & doing fetch manually, react-query is a must for any apps that does more than 3 API calls
- Wipe state when new data is received even if it's the same. My assumption is that you are merging API state & form state. API data should init the form and the form should have it own state. The form should only reset (or not, UX choice) when the initial data change

The second point is probably the main issue, it makes your app fragile to update and from that perspective I agree with the Next team on the "writing code resilient to occasional re-running of useEffect is a good practice". Is it a technical reason? Maybe, having the same code is not enough if for example your effect is referencing a global variable that was updated. The fact that after more than one year maintaining this plugin this is the first time I see an issue for that is giving me confidence that this ok and leeds to fewer unexpected states. This is what the React team learned, if one case is not correctly handled, people stop trusting HMR and do full reload which is worse.

Also because Vite doesn't bundle, updating components outside of the form file should only re-run the components in the edited file. If this is not the case you may breaking some fast refresh rules.

**Comment by jasekiw** [comment]
@ArnaudBarre Thanks for the response! That cleared up some of my questions.

I have a couple of responses to your assumptions:

> Missing client cache & doing fetch manually, react-query is a must for any apps that does more than 3 API calls

This app was created before react-query was mainstream. We are incrementally migrating pages to use react query. For legacy applications it's not exactly fair to expect them to be using it everywhere. 

> Wipe state when new data is received even if it's the same. My assumption is that you are merging API state & form state. API data should init the form and the form should have it own state. The form should only reset (or not, UX choice) when the initial data change

I am setting the form state mapped from the api state. It's not merging but rather replacing when the url changes. I am essentially setting `initialState` and calling reset on the form (using formik) to trigger it to use the `initialState`.  Since react-router does not remount the component, the form would never change it's data when navigated to a new page with the same component if there was no `useEffect` but if react-query was used and the same object was returned, you are right, this wouldn't be an issue.  I imagine legacy applications run into issues like this a lot since you need to rely on a library that was created after the system to cache data for you. For now we can use this workaround by checking the dependencies ourselves and use react query in any new development. What are your impressions?

Thanks again!

**Comment by ArnaudBarre** [comment]
Yeah I see you can do two things to improve this I think:
- Don't force reset the initialState, use `enableReinitialize` from formik and let formik diff if the initialData changed
- Take advantage of `key` to re-mount component when needed (not sure to understand exactly your problem with react-router, but if you want a component to re-mount when a prop change, create an intermediate wrapper and use this prop as a key): https://react.dev/reference/react/useState#resetting-state-with-a-key

**Comment by jasekiw** [comment]
@ArnaudBarre Thanks for the response! These are both possible solutions!  I didn't think about creating a wrapper component that takes the current url, that's a really good idea. I'll have to dig into the application a little more to see if this is easy to change but that should wrap up our conversation.

For anyone stumbling across this thread with a similar problem, see the solutions above. It sounds like the recommended approach is the avoid useEffect in cases like these to avoid breaking the DX.
