### ISSUE TITLE
Error when using block comments in JSX: "repeat count must be non-negative"

### ISSUE THREAD

**Issue by sidola** [vitejs/vite-plugin-react#272]
### Describe the bug

I'm encountering a bug on ^4.2.0 where if I'm using a block comment in JSX and have an additional block comment somewhere below it in the code babel blows up with the error "repeat count must be non-negative".

Minimal repro seems to be:
```tsx
export const App = () => {
  return (
    /* 
    This comment
    */
    <div>{'Hello world'}</div>
  );
};

/**
 * Plus this comment
 */
function someFunc() {
  // ...
}
```

I assume the culprit is some upstream babel dependency but I'm unsure exactly where to report it.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-fjadpp?file=index.html,src%2FApp.tsx,src%2Fmain.tsx&terminal=dev

### Steps to reproduce

Open the link and try running the app, error should appear in the console.

### System Info

```shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.4.2 - /usr/local/bin/npm
  pnpm: 8.10.5 - /usr/local/bin/pnpm
npmPackages:
  @vitejs/plugin-react: ^4.2.0 => 4.2.1 
  vite: ^5.0.4 => 5.0.6
```

### Used Package Manager

npm

### Logs
```
11:10:25 [vite] Internal server error: /home/projects/vitejs-vite-fjadpp/src/App.tsx: repeat count must be non-negative
  Plugin: vite:react-babel
  File: /home/projects/vitejs-vite-fjadpp/src/App.tsx
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This is a bug in Babel when using retainLines that was added recently to fix JSX source locations.
Thanks for making a small reproduction, I've reported it here: https://github.com/babel/babel/issues/16165

To work around you can:
- Patch @babel/code to not repeat 0 times if ident < 0
- Patch this plugin and disable the use of `retainLines`
- Try out the SWC plugin if you don't depend on something specific to Babel
- Avoid multi lines comments inside parentheses (maybe?, not exactly sure what triggers it)

**Comment by ArnaudBarre** [comment]
This should be fixed now!
