### ISSUE TITLE
Errors in react App.tsx file

### ISSUE THREAD

**Issue by shailesh1984** [vitejs/vite-plugin-react#275]
### Describe the bug

I have created sample react app using vite, but getting an errors in App.tsx file without modifying file.

![image](https://github.com/vitejs/vite-plugin-react/assets/6926778/d8165efe-e58a-4810-b685-213fa887697c)

![image](https://github.com/vitejs/vite-plugin-react/assets/6926778/5a001935-90f9-4b5c-a4c6-f8f6a9027364)

### Reproduction

no url

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 5.87 GB / 15.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    vite: ^5.0.8 => 5.0.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Most probably your VSCode version is outdated

**Comment by shailesh1984** [comment]
I have already updated the vscode(1.85).
