### ISSUE TITLE
Having "react" in optimizeDeps.include creates problems when "react" is externalized

### ISSUE THREAD

**Issue by MilanKovacic** [vitejs/vite-plugin-react#277]
### Describe the bug

Currently, plugin automatically sets react, and runtimes into [optimizeDeps.include](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts#L270).

When react is [externalized](https://github.com/MilanKovacic/vite-plugin-externalize-dependencies) during development (and for example, provided through import maps) this behavior is unwanted and results in various warnings / errors.

Is there a possibility that this behavior could be made opt-in, or something similar?

### Reproduction

Not relevant

### System Info

```shell
Not relevant
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
What's the need to externalized deps in dev?

**Comment by MilanKovacic** [comment]
One of the common use cases is when utilizing microfrontends architecture, where all microfrontends consume the same version of "react", for example, provided through import maps — to avoid issues with multiple instances of react.

Discussions on this topic:

 https://github.com/vitejs/vite/issues/6582
 https://github.com/vitejs/vite/issues/2483

**Comment by ArnaudBarre** [comment]
Yeah as you encounter this kind of need (micro-frontend, module federation, multiple dev server in dev, ...) is not supported by Vite today. I think @yyx990803 wants that to be better supported in the revamp with Rolldown, but until I'm not personally willing to add support for these feature requests that feels like Conway's low for me.
As already mentioned in multiple other issues, Vite is really flexible as soon as your keep one dev server, and you can have an index.html with `<div id="app1"></div><div id="app1"></div>` and an `index.tsx` with `import "../../app1/src/index.tsx"; import "../../app2/src/index.tsx";` that will boot both apps.

Anyway, if really you want to go forward with this separation of dev-servers, you can inject a plugin that does something like:
```ts
{
  name: "remove-react-optimized",
  config(config) {
    config.optimizeDeps.include = config.optimizeDeps.include.filter(
      (d) => d !== 'react' && !d.startsWith("react/"),
    )
  }
}
```

(Not tested but should work when added after the react plugins)
