### ISSUE TITLE
Getting syntax error on react-redux-snackbar

### ISSUE THREAD

**Issue by MianAfzaalZahoor** [vitejs/vite-plugin-react#279]
### Describe the bug

On running ```npm run build```
I am getting the following parsing error for react-redux-snackbar

### Reproduction

 vite.new/react

### Steps to reproduce

npm run build

### System Info

```shell
MacBook Pro (Retina, 15-inch, Mid 2015) Version 12.7.2
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
[commonjs--resolver] Expression expected in /Users/dev/Documents/project/node_modules/react-redux-snackbar/src/components/Snackbar/Snackbar.js
file: /Users/dev/Documents/project/node_modules/react-redux-snackbar/src/components/Snackbar/Snackbar.js:113:3
111:     const button = (snack.data.button || {}).label ? snack.data.button : null;
112:     return (
113:       <div
           ^
114:         style={this.populateStyles('snack')}
115:         onTransitionEnd={this.transitionEndHandler}
error during build:
RollupError: Expression expected in /Users/dev/Documents/project/node_modules/react-redux-snackbar/src/components/Snackbar/Snackbar.js
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This is because of this line: https://github.com/wireforce/react-redux-snackbar/blob/master/package.json#L7

The package says that the ESM version of the lib is an `.js` containing `.jsx` which is not a good practice and not something that should be shipped. Given that the lib was published 7 years ago, I think you should find something else, import the source code or fork it.
