### ISSUE TITLE
React Carbon Components <CodeSnippet> Errors Out on Vite Production Build Only But Works on Dev

### ISSUE THREAD

**Issue by mplatt212** [vitejs/vite-plugin-react#28]
### Describe the bug

I am part of a team that has started work on a preexisting React/Vite project that uses Carbon Components.  All is well until Docker serves Nginx with a production build and the <CodeSnippet> component produces the following error:
![image](https://user-images.githubusercontent.com/70013024/200419078-d4e60d0b-f369-4984-a8b7-292f46d3b73d.png)

This is even while just trying to render a simple string:
![image](https://user-images.githubusercontent.com/70013024/200419253-2e0cbde9-4d4c-4529-b547-13ba6f44da4d.png)

The strange thing is that this only seems to affect the <CodeSnippet> component and none of the other Carbon Components I have on the page.  I've made a simple reproduction in StackBlitz as closely as I could without running it through Docker and Nginx.  Running a Vite Build and then Vite Preview sometimes it seems to work but other times is doesn't render to the screen at all but without any errors.

vite.config.ts
![image](https://user-images.githubusercontent.com/70013024/200420169-40a69e4f-efcb-45db-b1ad-a2fa4fa85f04.png)

package.json
![image](https://user-images.githubusercontent.com/70013024/200420449-3f8f0cee-29e3-4b05-98f4-581f6475230b.png)
![image](https://user-images.githubusercontent.com/70013024/200420509-bda5ad29-bf15-41b8-bb54-679286987994.png)
![image](https://user-images.githubusercontent.com/70013024/200420541-107f2c5e-93af-4d44-b1d8-c0a380d6a81f.png)
![image](https://user-images.githubusercontent.com/70013024/200420565-4ad6c9d7-b388-4205-a6d6-72e09676b242.png)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-cygruj?file=package.json,vite.config.ts,src%2Fmain.tsx,index.html,src%2FApp.tsx&terminal=dev

### Steps to reproduce

vite build
vite preview

### System Info

```shell
Windows 10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by haoqunjiang** [comment]
Root cause:
`<CodeSnippet>` uses `use-resize-observer/polyfilled` (version 6) which depends on `resize-observer-polyfill`: https://unpkg.com/browse/use-resize-observer@6.1.0/polyfilled.js
which returns the global ResizeObserver constructor when it's available: https://github.com/que-etc/resize-observer-polyfill/blob/4a148452494a155656e4d04b9732b5914896b2e0/src/index.js#L4
As it's a UMD module, it's transformed by `@rollup/plugin-commonjs` on building, which would add a `getAugmentedNamespace()` wrapper (https://github.com/rollup/plugins/blob/master/packages/commonjs/src/helpers.js#L37), which doesn't handle the `new` case.

Could be easily fixed in Rollup.

**Comment by haoqunjiang** [comment]
Fixed in `@rollup/plugin-commonjs` v23.0.3, which is included in `vite` v4.0.0-alpha.6.

**Comment by vctqs1** [comment]
> Fixed in `@rollup/plugin-commonjs` v23.0.3, which is included in `vite` v4.0.0-alpha.6.

i'm using vite@v3, do we have an update in v3?

**Comment by haoqunjiang** [comment]
Vite 4 contains very few breaking changes, so I recommend upgrading to it if possible.

If not, you can open a PR in the Vite repository to backport the dependency upgrade to the `v3` branch.
