### ISSUE TITLE
Vite on M1 pro - This localhost page can’t be found

### ISSUE THREAD

**Issue by vishnnarayanan** [vitejs/vite-plugin-react#282]
### Describe the bug

I am running a Vite with below configuration. In terminal everything is good,
  VITE v4.5.2  ready in 279 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

But i cant able to run in browser. it shows "This localhost page can’t be found"

### Reproduction

NA

### Steps to reproduce

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import { checker } from 'vite-plugin-checker';
import { fetch } from 'cross-fetch';

global.fetch = fetch;

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		react({
			babel: {
				plugins: ['@babel/plugin-syntax-import-assertions'],
			},
		}),
		checker({
			typesript: true,
		}),
	],
	test: {
		include: ['**/*.test.tsx'],
		environment: 'jsdom',
		setupFiles: './src/setupTests.ts',
		globals: true,
		coverage: {
			reporter: ['text', 'cobertura', 'json', 'html', 'clover'],
		},
	},
});

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 798.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.2.1 
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6 
    @vitejs/plugin-react-swc: ^3.3.2 => 3.5.0 
    vite: ^4.4.9 => 4.5.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vishnnarayanan** [comment]
I tried running in Node 21 also.

**Comment by ArnaudBarre** [comment]
I can't debug your personal setup for you. Try starting from scratch with [create-vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project), if it still doesn't work, you have something on your computer that blocks localhost or this port. You can try using [another port](https://vitejs.dev/config/server-options.html#server-port)
