### ISSUE TITLE
use @vite/plugin-react build, sometime useEffect hook cleanup does not work.

### ISSUE THREAD

**Issue by aikilan** [vitejs/vite-plugin-react#29]
### Describe the bug

when I use @vite/plugin-react build project, I impot antd Form component in my project, when run "dist" in my server,  deps is empty array useEffect cleanup is not work.

I find reason, because @vite/plugin-react default use 'jsxruntime', when set this options {jsxRuntime: 'classic'}, the cleanup is on work!

### Reproduction

https://codesandbox.io/p/sandbox/sleepy-hodgkin-lpc40v?file=%2Fvite.config.ts&selection=%5B%7B%22endColumn%22%3A8%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A8%2C%22startLineNumber%22%3A11%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl95khku20012luip4301gyja%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252Fmain.tsx%2522%252C%2522%252Fsrc%252FApp.tsx%2522%252C%2522%252Fvite.config.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl9s933rs000k306is9uxb2yb%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
    Memory: 1.24 GB / 15.74 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-legacy: ^2.3.0 => 2.3.0
    @vitejs/plugin-react: ^2.2.0 => 2.2.0
    vite: ^3.2.0 => 3.2.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hey just tested inside codesanbox and the reset button is working in both case from my testing.

If you think there is an issue with useEffect in automatic runtime, this is either an issue with the lib (most probably) or with React (very low given the size of FB internal codebase).

While there is a very small chance a an error introduce by a minification issue, I think more people would have encounter it in the last months, so I'm closing for now. If you think this is the case, please provide an updated example on Stackblitz (can't download project on codesandbox 😕)
