### ISSUE TITLE
Default ESLint setup ignores JSX files if you run `npx eslint .`

### ISSUE THREAD

**Issue by phoenixeliot** [vitejs/vite-plugin-react#290]
### Describe the bug

If you set up a new Vite project using `npm create vite@latest`, the skeleton it generates will only lint JSX files if you run `npm run lint`, but will silently ignore JSX files if you run `npx eslint .`.

Since `npx eslint .` is a common way to run eslint, I think Vite's default setup should support that way of running it, instead of simply ignoring JSX files and giving the false impression it checked those.

(The supported way to run eslint is the `npm run lint` script Vite adds, but it's easy to not notice that should be used, and it's bad that not realizing that exists results in potentially a bunch of false negatives)

### Reproduction

https://github.com/phoenixeliot/vite-eslint-jsx-demo

### Steps to reproduce

1. Run `npm create vite@latest`. Select "React" and "Javascript" in the prompts.
2. Add this line to App.jsx, which violates an eslint:recommended rule: `for (var i = 0; i < 10; i--) { }`
3. Run `npx eslint .` in the terminal

Result: No errors are shown.

4. Run `npm run lint`

Result: This time, a lint error is shown.

However, if we add this to .eslintrc.cjs, `npx eslint .` works:
```js
  overrides: [
    {
      // This is required for `npx eslint .` to lint jsx files
      files: ["*.js", "*.jsx"],
    },
  ],
```

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 89.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    pnpm: 7.18.2 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 121.1.62.162
    Chrome: 121.0.6167.184
    Edge: 117.0.2045.31
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This will be fixed when switching to the new config format: https://github.com/vitejs/vite/pull/12860/files?w=1#diff-092d5a77b6c0bc902e62f6b81352d52c35f1ffc295dc5e26e07c438ba9076d1aR9

**Comment by phoenixeliot** [comment]
Ah, nice. Looking forward to it.

**Comment by ArnaudBarre** [comment]
I'm closing this because this not actionnable from here. You can open a PR to vite core to update the template and ping me in it, but I hope it doesn't get too long to have eslint v9 working with the react plugin and then we will merge the PR to use v9!
