### ISSUE TITLE
Does the React plugin not support React 16? I couldn't find related documentation.

### ISSUE THREAD

**Issue by GRAMMAC1** [vitejs/vite-plugin-react#297]
### Describe the bug

It seems that `1.0.0` already uses the JSX runtime. Does this mean that support for React 16 has been abandoned?

### Reproduction

none

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) x64 Apple M1 Pro
    Memory: 48.74 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.11.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1
    vite: ^5.1.4 => 5.1.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Yeah I should document it. This plugin only make sense if your version of React support Fast Refresh, which means >= 16.9 IIRC.
JSX runtime was introduced in 17 IIRC, with this plugin you can get back to default JSX transform with jsxRuntime option.

I'll keep this one open and update the Readme next time I do a change
