### ISSUE TITLE
Conflict with plugin-vue-jsx

### ISSUE THREAD

**Issue by gliheng** [vitejs/vite-plugin-react#303]
### Describe the bug

I have a monorepo with some files using vue-jsx, and some uing react. I set include option for both plugins. But they still seem to conflict, triggering build error.

### Reproduction

https://github.com/gliheng/vite-react-and-vue

### Steps to reproduce

pnpm i and open http://localhost:5173/
In vite.config.ts, plugin-vue-jsx and plugin-react only one can be enabled, not both.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.35 GB / 15.86 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 123.0.6312.86
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Logs

error during build:
RollupError: [vite:build-import-analysis] [plugin vite:build-import-analysis] src/react-app/main.tsx (9:22): Failed to parse source for import analysis because the content contains invalid JS syntax. If you use tsconfig.json, make sure to not set jsx to preserve.
file: C:/Users/juju/Learn/gaga-react/src/react-app/main.tsx:9:22
 7:   <React.StrictMode>
 8:     <App />
 9:   </React.StrictMode>,
                          ^
10: )
    at getRollupError (file:///C:/Users/juju/Learn/gaga-react/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at error (file:///C:/Users/juju/Learn/gaga-react/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at Object.error (file:///C:/Users/juju/Learn/gaga-react/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/node-entry.js:19410:20)
    at Object.error (file:///C:/Users/juju/Learn/gaga-react/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/node-entry.js:18520:42)
    at Object.transform (file:///C:/Users/juju/Learn/gaga-react/node_modules/.pnpm/vite@5.2.0/node_modules/vite/dist/node/chunks/dep-B8QpfTwU.js:66540:22)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Sorry I didn't have time to look at it yet. Did you find a solution?

**Comment by gliheng** [comment]
The problem I think is on vue plugins's side, thus I closed this issue and opened one of plugin-vue's side. https://github.com/vitejs/vite-plugin-vue/issues/391
