### ISSUE TITLE
gettting jsxDev is not defined error while using LexicalRichTextPlugin in react 

### ISSUE THREAD

**Issue by YogiDhingani27** [vitejs/vite-plugin-react#308]
### Describe the bug

vite version: ^2.8.0
@vitejs/plugin-react: ^1.0.7

![image](https://github.com/vitejs/vite-plugin-react/assets/94128664/18e01d96-279c-43cf-b548-240798ef90bc)

![image](https://github.com/vitejs/vite-plugin-react/assets/94128664/c0baecdb-3e13-48a2-a93d-78e228e182ed)

![image](https://github.com/vitejs/vite-plugin-react/assets/94128664/b39448ac-d198-458e-9e2f-8293e4afeabf)

I'm facing this issue only in pages where Lexical editor is used. Other pages working fine.

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
Vite 2 won't be updated anymore.
https://vitejs.dev/releases.html#:~:text=The%20previous%20Vite%20Major%20will%20keep%20receiving%20important%20fixes%20and%20security%20patches.%20After%20that%2C%20it%20would%20only%20get%20updates%20if%20there%20are%20security%20concerns.
