### ISSUE TITLE
Could not resolve !!raw-loader!prismjs

### ISSUE THREAD

**Issue by moosubb4** [vitejs/vite-plugin-react#309]
### Describe the bug

before I migrate project builder tools from craco to Vite `react-prism-editor` it work well but when change to Vite I got problem 

`node_modules/react-prism-editor/lib/getPrismSource.js`
 cannot found path from !!raw-loader!

<img width="852" alt="image" src="https://github.com/vitejs/vite-plugin-react/assets/25027115/3468e452-4d93-4f46-9fe7-833a7a3acda9">

error when building and I try to config optimizeDeps.esbuildOptions.exclude 

<img width="610" alt="image" src="https://github.com/vitejs/vite-plugin-react/assets/25027115/f2bf9df8-0529-4f91-b05f-b9abd2c64b8e">

it build find but I got error again

<img width="889" alt="image" src="https://github.com/vitejs/vite-plugin-react/assets/25027115/c6888b63-7c23-41fa-a56e-6c397efde4c2">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-yrbe4u

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) x64 Apple M2
    Memory: 32.22 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/Library/pnpm/node
    Yarn: 1.22.22 - ~/Work/connect-x-front/node_modules/.bin/yarn
    npm: 8.19.2 - ~/Library/pnpm/npm
    pnpm: 7.13.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4
  npmPackages:
    @vitejs/plugin-legacy: ^5.3.2 => 5.3.2 
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    vite: ^5.0.8 => 5.2.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I don't know what is this syntax but it's not standard at all and probably something webpack only. Did you look for people having the same issue on the lib issues?

**Comment by moosubb4** [comment]
> I don't know what is this syntax but it's not standard at all and probably something webpack only. Did you look for people having the same issue on the lib issues?

yep but not found anything, I think the problem is caused by when pre-bundling !!raw-loader!prism not building

**Comment by ArnaudBarre** [comment]
Pre-bundling or not, the lib source code contains import that contains webpack only import style. You need to ask the library to update their code to use esm or cjs import and ask user to load the CSS on their own (using esm/cjs import for CSS would work in Vite but I would not recommend it and let users have more control on how they bundle the JS and the CSS part)

**Comment by moosubb4** [comment]
> Pre-bundling or not, the lib source code contains import that contains webpack only import style. You need to ask the library to update their code to use esm or cjs import and ask user to load the CSS on their own (using esm/cjs import for CSS would work in Vite but I would not recommend it and let users have more control on how they bundle the JS and the CSS part)

now I change lib to [react-ace](https://github.com/securingsincity/react-ace) it work well
and `react-prism-editor` is no longer supported thanks guys
