### ISSUE TITLE
App crashing on production build when using react-export-excel

### ISSUE THREAD

**Issue by aviyi** [vitejs/vite-plugin-react#31]
### Describe the bug

I'm try to move my react app to use vite instead of create-react-app
I'm using package call react-export-excel to export some data. 
Everything work Ok on development mode  .
When I'm try to build my app I'm getting an error "Uncaught Error: Could not dynamically require "./jszip". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
"

### Reproduction

https://github.com/aviyi/vite-xlsx

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 16.97 GB / 31.77 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^2.0.0 => 2.0.0
    vite: ^3.0.0 => 3.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bluwy** [comment]
Looks like the core issue comes from this [hacky code](https://github.com/securedeveloper/js-xlsx/blob/32f550d3b3bdb1b781aabe100683311cd982c98e/xlsx.js#L1344-L1345) from js-xlsx. Can't seem to workaround it though from some light testing.

**Comment by ArnaudBarre** [comment]
Yeah I blown away that esbuild succeed to bundle this correctly in dev.

I think this is the kind of issue that would be a wontfix. I think we should not support every weird things people come up with webpack along the years. 

Note: A solution for you would be to fork the lib and make it ESM friendly

**Comment by ArnaudBarre** [comment]
From the beginning Vite plan was never to fully replace all of what webpack does, like supporting all this pre-ESM hacks.

Closing as won't fix.
