### ISSUE TITLE
ESBuild supports decorators now

### ISSUE THREAD

**Issue by pnegahdar** [vitejs/vite-plugin-react#314]
### Description

ESBuild added support for decorators in 0.21. Hopefully this means a lot of projects can kill their usage of babel. 

https://github.com/evanw/esbuild/issues/104#issuecomment-2097359571

I attempted to simply drop the babel config in the `react()` plugin and set the `esbuild: {target: "es2022"}` and that didn't seem to work.

Do we have to wait for a new release or can we force it to use the feature with the right configuration? It's not clear to me how the puglin decides whether to use babel or not (it seems to even when I don't have have a babel config it does. 

### Suggested solution

Describe configuration to use latest esbuild with decorator support or bump the package? 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
You will need Vite to ship the new version of esbuild that was marked as breaking change by safety by Evan Wallace. This is plan for 5.3 that should be shipped this month. You can follow this issue for updates: https://github.com/vitejs/vite/issues/16616
