### ISSUE TITLE
Running React Compiler not successful

### ISSUE THREAD

**Issue by williamlsh** [vitejs/vite-plugin-react#322]
### Describe the bug

Running React Compiler according to [official guide](https://react.dev/learn/react-compiler#usage-with-vite) on an existing React + Vitejs project not successful.

Running `react-compiler-healthcheck@latest` already pass.

`babel-plugin-react-compiler` already installed.

`vite-plugin-react` plugin already installed.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-33dfp4?file=vite.config.ts

### Steps to reproduce

npm run dev

### System Info

```shell
Linux
```

### Used Package Manager

npm

### Logs

[plugin:vite:import-analysis] Missing "./compiler-runtime" specifier in "react" package

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
You need to run `npm install -D babel-plugin-react-compiler`.
Also you need to upgrade react to v19 beta.
https://react.dev/learn/react-compiler#:~:text=React%20Compiler%20requires%20React%2019%20Beta.

**Comment by williamlsh** [comment]
Indeed, it works after upgrading to React 19 beta.
