### ISSUE TITLE
The 4.3.0 version break React compiler setup

### ISSUE THREAD

**Issue by iahu** [vitejs/vite-plugin-react#328]
### Describe the bug

update to the 4.3.0 and run vite dev server will catch an error:
```sh
error when starting dev server:
Error: Missing "./compiler-runtime" specifier in "react" package
    at e (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:25)
    at n (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:627)
    at o (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:1297)
    at resolveExportsOrImports (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48287:20)
    at resolveDeepImport (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48306:31)
    at tryNodeResolve (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
    at Context.resolveId (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
    at Object.resolveId (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
    at async file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68310:21
    at async file:///project/workspace/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51735:20
```

### Reproduction

https://codesandbox.io/p/devbox/react-18-react-compiler-tdrjxf?file=%2Fpackage.json%3A15%2C35

### Steps to reproduce

make sure "@vitejs/plugin-react" version is "4.3.0" in package.json, run `yarn install` and `yarn dev`.

to compare with the version "4.2.1", rewrite the "@vitejs/plugin-react" version to "4.2.1" in package.json, and re-run `yarn install` and `yarn dev`

### System Info

```shell
System:
OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
CPU: (2) x64 AMD EPYC
Memory: 989.90 MB / 4.01 GB
Container: Yes
Shell: Unknown
Binaries:
Node: 20.9.0 - /usr/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn npm: 9.8.1 - /usr/local/bin/npm
pnpm: 8.10.2 - /usr/local/share/npm-global/bin/pnpm nomPackages:
@vitejs/plugin-react: 4.3.0 => 4.3.0
vite: 5.2.11 => 5.2.11
```

### Used Package Manager

yarn

### Logs

yarn run v1.22.22
$ vite
error when starting dev server:
Error: Missing "./compiler-runtime" specifier in "react" package
    at e (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:25)
    at n (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:627)
    at o (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:1297)
    at resolveExportsOrImports (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48287:20)
    at resolveDeepImport (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48306:31)
    at tryNodeResolve (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
    at Context.resolveId (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
    at Object.resolveId (file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
    at async file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68310:21
    at async file:///Users/hu/Developer/react-comipler-demo-2/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51735:20
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
The link is not working.
I think this happening because you are using the compiler with React 18, which is not supported I think

**Comment by iahu** [comment]
> The link is not working. I think this happening because you are using the compiler with React 18, which is not supported I think

Sorry, my bad. have make it public now

[click here](https://codesandbox.io/p/devbox/react-18-react-compiler-tdrjxf?file=%2Fpackage.json%3A15%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwpr6zqv00063b6ghjnbxpjc%2522%252C%2522sizes%2522%253A%255B56.49289099526065%252C43.50710900473935%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwpr6zqu00023b6g3mmhoclk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwpr6zqu00043b6g81fjleu9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwpr6zqu00053b6gtbvlbe0g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwpr6zqu00023b6g3mmhoclk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwpr6zqu00013b6g3coluh5q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A35%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwpr6zqu00023b6g3mmhoclk%2522%252C%2522activeTabId%2522%253A%2522clwpr6zqu00013b6g3coluh5q%2522%257D%252C%2522clwpr6zqu00053b6gtbvlbe0g%2522%253A%257B%2522id%2522%253A%2522clwpr6zqu00053b6gtbvlbe0g%2522%252C%2522activeTabId%2522%253A%2522clwpv4a0800jz3b6grh7y595n%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clwpv4a0800jz3b6grh7y595n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clwpr6zqu00043b6g81fjleu9%2522%253A%257B%2522id%2522%253A%2522clwpr6zqu00043b6g81fjleu9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwpr6zqu00033b6gd4jq04h1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwpr706f000odsf82bkn58e9%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwpt9mm101e43b6gth73ejt5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520install%2520vite%25405.2.11%2522%252C%2522id%2522%253A%2522clwpt9mx901fo3b6gd7mzopfn%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwpr6zqu00033b6gd4jq04h1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to view
