### ISSUE TITLE
Using a freshly generated react-ts project in a traditional backend: @vitejs/plugin-react can't detect preamble

### ISSUE THREAD

**Issue by stonetwig** [vitejs/vite-plugin-react#336]
### Describe the bug

I used the Vite template in order to generate a React TypeScript app:
`npm create vite@latest my-app -- --template react-ts`

I want to load the app in a traditional server-side generated backend. So I followed the guide [here](https://vitejs.dev/guide/backend-integration). 

I have the following in the `<head>`:
```
<script type="module">
			import RefreshRuntime from 'http://localhost:5173/@react-refresh'
			RefreshRuntime.injectIntoGlobalHook(window)
			window.$RefreshReg$ = () => {}
			window.$RefreshSig$ = () => (type) => type
			window.__vite_plugin_react_preamble_installed__ = true
		</script>
		<script type="module" src="http://localhost:5173/@vite/client"></script>
```

And then this in the "content" area:

```
<div id="root"></div>
<script type="module" src="http://localhost:5173/src/main.tsx"></script>
```

All files loads perfectly fine and all, but I recieve an error in the console:
```
App.tsx:1 Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at App.tsx:1:33
```

The discussion linked seems unrelevant to my issue and I have put `import 'vite/modulepreload-polyfill'` in the top of my main.tsx file.

What do I do wrong here? Seems like this is broken somehow.
I have fiddled with different Vite settings but nothing seems to help. 

I have checked https://github.com/vitejs/vite-plugin-react/issues/11 but it seems like it is not really relevant to this, even if the same error occurs?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hoqkej?file=src%2Fmain.tsx

### Steps to reproduce

1. Generate a new react-ts project with vite
2. Do steps 1 and 2 from https://vitejs.dev/guide/backend-integration

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 140.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 124.1.65.133
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.3.1
    vite: ^5.2.0 => 5.2.13
```

### Used Package Manager

npm

### Logs

<details>

vite:config bundled config file loaded in 43.64ms +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:optimized-deps',
  vite:config     'vite:watch-package-data',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:client-inject',
  vite:config     'vite:css-analysis',
  vite:config     'vite:import-analysis'
  vite:config   ],
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     sourcemap: false,
  vite:config     rollupOptions: { input: '/src/main.tsx', onwarn: [Function: onwarn] },
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: true,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true },
  vite:config     cssMinify: true
  vite:config   },
  vite:config   optimizeDeps: {
  vite:config     holdUntilCrawlEnd: true,
  vite:config     force: undefined,
  vite:config     esbuildOptions: { preserveSymlinks: false, jsx: 'automatic' },
  vite:config     include: [ 'react', 'react/jsx-dev-runtime', 'react/jsx-runtime' ]
  vite:config   },
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     host: undefined,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules$1],
  vite:config     middlewareMode: false,
  vite:config     fs: {
  vite:config       strict: true,
  vite:config       allow: [Array],
  vite:config       deny: [Array],
  vite:config       cachedChecks: undefined
  vite:config     }
  vite:config   },
  vite:config   esbuild: { jsxDev: true, jsx: 'automatic', jsxImportSource: undefined },
  vite:config   resolve: {
  vite:config     mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
  vite:config     conditions: [],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object] ]
  vite:config   },
  vite:config   configFile: '/Users/user/code/project/vite.config.ts',
  vite:config   configFileDependencies: [ '/Users/user/code/project/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     server: { host: undefined }
  vite:config   },
  vite:config   root: '/Users/user/code/project',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/Users/user/code/project/public',
  vite:config   cacheDir: '/Users/user/code/project/node_modules/.vite',
  vite:config   command: 'serve',
  vite:config   mode: 'development',
  vite:config   ssr: {
  vite:config     target: 'node',
  vite:config     optimizeDeps: { noDiscovery: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   bundleChain: [],
  vite:config   isProduction: false,
  vite:config   css: { lightningcss: undefined },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   envDir: '/Users/user/code/project',
  vite:config   env: { BASE_URL: '/', MODE: 'development', DEV: true, PROD: false },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {
  vite:config     'fnpd_/Users/user/code/project' => {
  vite:config       dir: '/Users/user/code/project',
  vite:config       data: [Object],
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       webResolvedImports: {},
  vite:config       nodeResolvedImports: {},
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: { format: 'iife', plugins: '() => plugins', rollupOptions: {} },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +2ms
  vite:deps Hash is consistent. Skipping. Use --force to override. +0ms

  VITE v5.2.13  ready in 119 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
  vite:time 2.31ms / +0ms
  vite:resolve 2.75ms /@vite/client -> /Users/user/code/project/node_modules/vite/dist/client/client.mjs +0ms
  vite:resolve 0.77ms /src/main.tsx -> /Users/user/code/project/src/main.tsx +5ms
  vite:load 1.01ms [fs] /src/main.tsx +0ms
  vite:load 216.34ms [fs] /@vite/client +211ms
  vite:load 0.04ms [plugin] /@react-refresh +2ms
  vite:resolve 0.08ms @vite/env -> /Users/user/code/project/node_modules/vite/dist/client/env.mjs +220ms
  vite:import-analysis 1.27ms [1 imports rewritten] node_modules/vite/dist/client/client.mjs +0ms
  vite:transform 2.02ms /@vite/client +0ms
  vite:time 230.65ms /@vite/client +388ms
  vite:import-analysis 0.35ms [0 imports rewritten] /@react-refresh +3ms
  vite:transform 8.37ms /@react-refresh +2ms
  vite:time 8.81ms /@react-refresh +2ms
  vite:load 2.65ms [fs] /node_modules/vite/dist/client/env.mjs +9ms
  vite:import-analysis 0.02ms [no imports] node_modules/vite/dist/client/env.mjs +1ms
  vite:transform 0.12ms /node_modules/vite/dist/client/env.mjs +1ms
  vite:cache [304] /node_modules/vite/dist/client/env.mjs +0ms
  vite:time 0.06ms /node_modules/vite/dist/client/env.mjs +2ms
  vite:resolve 0.14ms vite/modulepreload-polyfill -> vite/modulepreload-polyfill.js +6ms
  vite:resolve 0.35ms ./App.tsx -> /Users/user/code/project/src/App.tsx +0ms
  vite:resolve 0.37ms ./index.css -> /Users/user/code/project/src/index.css +0ms
  vite:resolve 0.40ms react/jsx-dev-runtime -> /Users/user/code/project/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +0ms
  vite:resolve 0.45ms react -> /Users/user/code/project/node_modules/.vite/deps/react.js?v=942ca6dd +0ms
  vite:resolve 0.46ms react-dom/client -> /Users/user/code/project/node_modules/.vite/deps/react-dom_client.js?v=942ca6dd +0ms
  vite:import-analysis /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd needs interop +3ms
  vite:import-analysis /node_modules/.vite/deps/react.js?v=942ca6dd needs interop +1ms
  vite:import-analysis /node_modules/.vite/deps/react-dom_client.js?v=942ca6dd needs interop +1ms
  vite:load 2.08ms [plugin] vite/modulepreload-polyfill.js +6ms
  vite:optimize-deps load /Users/user/code/project/node_modules/.vite/deps/react_jsx-dev-runtime.js +0ms
  vite:optimize-deps load /Users/user/code/project/node_modules/.vite/deps/react.js +0ms
  vite:optimize-deps load /Users/user/code/project/node_modules/.vite/deps/react-dom_client.js +0ms
  vite:import-analysis 3.05ms [6 imports rewritten] src/main.tsx +0ms
  vite:transform 228.66ms /src/main.tsx +6ms
  vite:time 231.74ms /src/main.tsx +5ms
  vite:import-analysis 0.01ms [no imports] vite/modulepreload-polyfill.js +2ms
  vite:transform 1.82ms vite/modulepreload-polyfill.js +1ms
  vite:load 4.61ms [plugin] /node_modules/.vite/deps/react.js?v=942ca6dd +4ms
  vite:resolve 0.13ms ./chunk-HZASMJ22.js -> /Users/user/code/project/node_modules/.vite/deps/chunk-HZASMJ22.js?v=942ca6dd +8ms
  vite:optimize-deps load /Users/user/code/project/node_modules/.vite/deps/chunk-HZASMJ22.js +5ms
  vite:import-analysis 0.49ms [1 imports rewritten] node_modules/.vite/deps/react.js?v=942ca6dd +3ms
  vite:transform 0.54ms /node_modules/.vite/deps/react.js?v=942ca6dd +3ms
  vite:load 5.24ms [plugin] /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +1ms
  vite:import-analysis 0.32ms [1 imports rewritten] node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +1ms
  vite:transform 0.45ms /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +1ms
  vite:time 1.22ms /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +5ms
  vite:load 6.00ms [fs] /src/App.tsx +1ms
  vite:load 15.81ms [fs] /src/index.css +10ms
  vite:hmr [self-accepts] src/index.css +0ms
  vite:import-analysis 0.24ms [0 imports rewritten] src/index.css +10ms
  vite:transform 0.69ms /src/index.css +10ms
  vite:cache [memory] /node_modules/.vite/deps/react.js?v=942ca6dd +0ms
  vite:time 0.08ms /node_modules/.vite/deps/react.js?v=942ca6dd +11ms
  vite:load 18.14ms [plugin] /node_modules/.vite/deps/react-dom_client.js?v=942ca6dd +2ms
  vite:import-analysis 6.26ms [1 imports rewritten] node_modules/.vite/deps/react-dom_client.js?v=942ca6dd +11ms
  vite:transform 8.67ms /node_modules/.vite/deps/react-dom_client.js?v=942ca6dd +11ms
  vite:time 11.98ms /node_modules/.vite/deps/react-dom_client.js?v=942ca6dd +13ms
  vite:resolve 0.47ms ./assets/react.svg -> /Users/user/code/project/src/assets/react.svg +28ms
  vite:resolve 0.52ms ./App.css -> /Users/user/code/project/src/App.css +0ms
  vite:cache [memory] /@react-refresh +16ms
  vite:cache [memory] vite/modulepreload-polyfill.js +0ms
  vite:import-analysis /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd needs interop +7ms
  vite:import-analysis /node_modules/.vite/deps/react.js?v=942ca6dd needs interop +0ms
  vite:cache [memory] /node_modules/.vite/deps/react_jsx-dev-runtime.js?v=942ca6dd +1ms
  vite:cache [memory] /node_modules/.vite/deps/react.js?v=942ca6dd +0ms
  vite:hmr [self-accepts] src/App.tsx +18ms
  vite:import-analysis 1.85ms [7 imports rewritten] src/App.tsx +0ms
  vite:transform 28.75ms /src/App.tsx +8ms
  vite:load 0.80ms [plugin] /src/assets/react.svg +17ms
  vite:load 0.81ms [plugin] /vite.svg +0ms
  vite:import-analysis 0.01ms [no imports] src/assets/react.svg +1ms
  vite:import-analysis 0.00ms [no imports] /vite.svg +0ms
  vite:transform 0.13ms /src/assets/react.svg +0ms
  vite:transform 0.12ms /vite.svg +0ms
  vite:cache [304] /@id/__x00__vite/modulepreload-polyfill.js +39ms
  vite:time 0.03ms /@id/__x00__vite/modulepreload-polyfill.js +5ms
  vite:cache [memory] /src/App.tsx +2ms
  vite:time 0.19ms /src/App.tsx +1ms
  vite:load 31.43ms [plugin] /node_modules/.vite/deps/chunk-HZASMJ22.js?v=942ca6dd +1ms
  vite:import-analysis 1.23ms [no imports] node_modules/.vite/deps/chunk-HZASMJ22.js?v=942ca6dd +4ms
  vite:transform 2.14ms /node_modules/.vite/deps/chunk-HZASMJ22.js?v=942ca6dd +4ms
  vite:time 20.91ms /node_modules/.vite/deps/chunk-HZASMJ22.js?v=942ca6dd +3ms
  vite:cache [304] /src/index.css +4ms
  vite:time 0.12ms /src/index.css +0ms
  vite:cache [304] /src/assets/react.svg?import +1ms
  vite:time 0.02ms /src/assets/react.svg?import +1ms
  vite:cache [304] /vite.svg?import +0ms
  vite:time 0.02ms /vite.svg?import +0ms
  vite:load 6.50ms [fs] /src/App.css +5ms
  vite:hmr [self-accepts] src/App.css +7ms
  vite:import-analysis 0.15ms [0 imports rewritten] src/App.css +2ms
  vite:transform 0.36ms /src/App.css +2ms
  vite:time 0.69ms /src/App.css +1ms
  vite:cache [304] /@vite/client +4s
  vite:time 0.18ms /@vite/client +4s
  vite:cache [304] /src/main.tsx +1ms
  vite:time 0.08ms /src/main.tsx +1ms
  vite:cache [304] /node_modules/vite/dist/client/env.mjs +30ms
  vite:time 0.18ms /node_modules/vite/dist/client/env.mjs +30ms
  vite:cache [304] /src/App.tsx +1ms
  vite:time 0.06ms /src/App.tsx +1ms
  vite:cache [304] /@id/__x00__vite/modulepreload-polyfill.js +0ms
  vite:time 0.05ms /@id/__x00__vite/modulepreload-polyfill.js +0ms
  vite:cache [304] /src/index.css +1ms
  vite:time 0.37ms /src/index.css +1ms
  vite:cache [304] /@react-refresh +0ms
  vite:time 0.06ms /@react-refresh +0ms
  vite:cache [304] /src/assets/react.svg?import +4ms
  vite:time 0.08ms /src/assets/react.svg?import +4ms
  vite:cache [304] /vite.svg?import +0ms
  vite:time 0.08ms /vite.svg?import +0ms
  vite:cache [304] /src/App.css +0ms
  vite:time 0.12ms /src/App.css +0ms

</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Part 1 of the documentation you reference https://vitejs.dev/guide/backend-integration is only for build, so what matter is actually only Part 2 for development.

"Do steps 1 and 2" totally depends on your SSR framework, so you probably need to provide your code for us to investigate the issue further.

One possible issue is that it's common to have some race condition between two `<script>`, so you might need to make sure first `@react-refresh` part is done before going for `/src/main.tsx`.

One thing you could try (to verify the issue at least) is something like:

```html
<script type="module">
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
  
   // move client entry in the same `script` as dynamic import
  import("/src/main.tsx")
</script>
```

---

By the way, the link in the error message seems wrong indeed, but not sure what it's supposed to be. I think this link is mixed up while moving the plugin code around multiple repositories.

**Comment by stonetwig** [comment]
Thanks for the reply and I think you were correct in your assumption. Unfortunately is the code quite old and part of a sophisticated code base that is hard to break down so that's why I didn't include any backend code to my report. Sorry for that.

It worked fine with the import statement so it must be a race condition as you've said even if I wonder how that could've happened.

Big thanks anyway!
