### ISSUE TITLE
Optimizing CSS File Size in Vite

### ISSUE THREAD

**Issue by harshitacodes** [vitejs/vite-plugin-react#342]
I'm trying to understand how my index.css is being generated. I know that Vite uses esbuild to build the file chunks. However, I want to reduce the size of index.css by removing some unused CSS during the build process. The current size of index.css is quite large, causing it to block other elements from loading and significantly impacting page performance.

Any suggestions on how to achieve this?

<img width="584" alt="Screenshot 2024-06-24 at 5 05 28 PM" src="https://github.com/vitejs/vite-plugin-react/assets/55912888/3ddd4d8a-7312-4ecb-8507-2ddfe1f9bc3f">

_Originally posted by @harshitacodes in https://github.com/vitejs/vite-plugin-react/discussions/341_

**Comment by Shakeskeyboarde** [comment]
That is huge for a css file... is the original that big? If not, are you somehow embedding data urls (images) in it?

**Comment by ArnaudBarre** [comment]
I can't really help here, the simplest way to understand what in there is to open it, run prettier on it and see look for reference to libraries or assets and maybe see duplicated sections and then try to debug why this is unexpectedly bundled.

**Comment by harshitacodes** [comment]
> That is huge for a css file... is the original that big? If not, are you somehow embedding data urls (images) in it?


Yes, I mean I am using images, but they are svgs. there are a lot of CSS modules being used in the project, but the issue is that Vite is somehow bundling similar files or CSS and putting them into these two files. I just want to know if there is any way to find out how Vite is creating this index.css file and what patterns it is using to generate it.

**Comment by ArnaudBarre** [comment]
If you load your JS into two big chunks, then Vite creates two big CSS chunks that where either imported by the JS files from the initial bundle or the second one. Codeplitting is always driven by JS imports

**Comment by harshitacodes** [comment]
if Codeplitting is always driven by JS imports, then how can we load only critical css? , is there a anyway to confirgue that in the vite configuration file, or any pluggin?

**Comment by ArnaudBarre** [comment]
You should always locate the CSS with the JS that needs it. Then you should use dynamic import to delay the use of non criticial JS

**Comment by harshitacodes** [comment]
Do you have any idea about this?
https://github.com/nystudio107/rollup-plugin-critical

I am trying to configure a plugin in vite.config.ts to reduce the size of the generated index.css file. This might help the page load faster by using only the critical CSS.

**Comment by ArnaudBarre** [comment]
What is the size of your JS? Except if you have megabytes of JS it's not normal to have so much CSS, you're probably bundling things that are unrelated or inlining fonts or images. You need to look for something useless in your CSS instead making the setup more complex

**Comment by harshitacodes** [comment]
these are the js file size:
build/assets/DragNDrop-3l72duiU.js                     102.86 kB │ gzip:  31.25 kB
build/assets/ManageTagsLayout-cWE2jd8G.js              154.03 kB │ gzip:  48.43 kB
build/assets/index-25I1hck2.js                         164.36 kB │ gzip:  50.12 kB
build/assets/index-klxukq7u.js                         255.36 kB │ gzip:  69.82 kB
build/assets/Introduction-Yz1cBlN-.js                  261.17 kB │ gzip:  70.20 kB
build/assets/index.es-_vCAeELF.js                      291.78 kB │ gzip:  83.54 kB
build/assets/prism-r-VQinFRPd.js                       371.91 kB │ gzip: 106.78 kB
build/assets/ColumnChart-2aeiSCld.js                   527.43 kB │ gzip: 138.19 kB
build/assets/TopBanner-5Bb6IeWJ.js                     571.84 kB │ gzip: 173.50 kB
build/assets/katex-t0ImUQoM.js                         740.44 kB │ gzip: 210.46 kB
build/assets/ace-b6WInI8p.js                           760.18 kB │ gzip: 210.14 kB
build/assets/CompetePage-ZylRwqJe.js                   791.01 kB │ gzip:  45.71 kB
build/assets/vendor-P-KBAHGa.js                        908.33 kB │ gzip: 282.56 kB


I have already separated the chunks of heavy files:

build: {
                outDir: './build',
                rollupOptions: {
                    output: {
                        // eslint-disable-next-line consistent-return
                        manualChunks(id: string): any {
                            // creating a chunk to Katex deps
                            const libraries =
                                [
                                    "@material-ui",
                                    "prismjs",
                                    "react-apexcharts",
                                    "react-csv",
                                    "moment",
                                    "sweetalert2",
                                    "katex",
                                    "ace-builds",
                                    "react-router-dom"
                                ];
                            if (libraries.some((libName) => id.includes(`node_modules/${libName}`))) {
                                return id.toString().split("node_modules/")[1].split("/")[0].toString();
                            }
                        },
                    },
                },
            },

**Comment by ArnaudBarre** [comment]
Ok so this is clearly an entreprise size application with already a non trivial build setup. I'm sorry but this not part of my open source work to help you optimize this kind of app.
