### ISSUE TITLE
HMR does not reload changes in default props

### ISSUE THREAD

**Issue by chawes13** [vitejs/vite-plugin-react#350]
### Describe the bug

I am changing the value of a default prop and seeing subsequent "hmr update" logs in the terminal. The new value of the prop does not show up in the component when no value is passed for the prop to the component (i.e., the default is used).

### Reproduction

https://stackblitz.com/edit/vitejs-vite-velxyz?file=src%2FApp.jsx

### Steps to reproduce

1. Update the value of `title` in `defaultProps`
2. Save
3. New value of title is not shown in the `<h1>`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1 
    vite: ^5.3.4 => 5.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
This is something that should be handled at the Fast Refresh level, but it's not and probably never will be because fast refresh was released in 2019, 4 years after default parameters have been a thing in the language. I'm quite impressed that this as not been deprecated yet.

You should rewrite your code like this
```js
function App({ title = 'Vite + React (test)!' }) {
```
and also consider using TS: 
```ts
function App({ title = 'Vite + React (test)!' }: { title?: string }) {
```

**Comment by chawes13** [comment]
Company constraints 🤷 . It works with Webpack, so it's a bit annoying to introduce this regression when switching build tools. Given that defaultProps are getting deprecated in v19, I'll move over to default parameters.
