### ISSUE TITLE
Env variable is being replace in build time

### ISSUE THREAD

**Issue by guidari** [vitejs/vite-plugin-react#357]
### Describe the bug

I am using [this config](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#babel) in my main.js to make the build to work. However, I have defined a global environment variable called `__DEV__` in my project, and this variable is being replaced at build time, resulting in the following error: `__DEV__ is not defined`.

![Screenshot 2024-08-13 at 17 01 27](https://github.com/user-attachments/assets/94b0c7d6-a87c-44b2-92cd-dc1f08336f1d)

With that in mind, we tried to define `__DEV__` in the main.js as follows:

```jsx
if (configType === 'DEVELOPMENT') {
      config.define = {
        __DEV__: 'true',
      };
    }
    if (configType === 'PRODUCTION') {
      config.define = {
        __DEV__: 'false',
      };
    }
```

However, a new error appears:

![Screenshot 2024-08-15 at 11 19 30](https://github.com/user-attachments/assets/0d45f0b7-9ca5-4360-a9e4-683b3603d89e)

How do we know this is replacing `__DEV__` ? We have a component called ModalWrapper that uses `__DEV__` and if we comment out the line with the variable, the errors goes away.

Here it is the [main.js](https://github.com/carbon-design-system/carbon/blob/75cc6935beeeaa0a8f52f8d1b01194fc3954d864/packages/react/.storybook/main.js) file in the last commit with the issue

We also tried to use our existing pipeline with `babel-plugin-dev-expression` but it didn't work.

Possible solution:
Maybe if we can enforce the order that babel will run we can fix it?
https://github.com/vitejs/vite-plugin-react/blob/daa5b620da8561cc999d195c5728f8419adf428a/packages/plugin-react/src/index.ts#L114

### Reproduction

https://github.com/carbon-design-system/carbon/pull/16910

### Steps to reproduce

I paste the PR I'm working on. You can check the error in the commit:
[fix: added babel back](https://github.com/carbon-design-system/carbon/pull/16910/commits/75cc6935beeeaa0a8f52f8d1b01194fc3954d864)
[75cc693](https://github.com/carbon-design-system/carbon/pull/16910/commits/75cc6935beeeaa0a8f52f8d1b01194fc3954d864)

Go to __Checks__ to see the CI error in [vrt-runner (4)](https://github.com/carbon-design-system/carbon/actions/runs/10405342800/job/28815868224?pr=16910)

### System Info

```shell
System:
    OS: macOS 14.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 32.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 4.2.2 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.120
    Firefox: 129.0.1
    Safari: 17.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
The reproduction has many moving parts (babel, custom esbuild config + vite is mainly driven by storybook) and I don't think it's easy to spot anything quickly. We'll probably need a reproduction outside of storybook at least.

Btw from your PR, it's not clear which version of Vite and plugins you're using (or automatically installed by storybook?). Please make sure to provide the information.

I haven't tried to run your PR locally yet, but one thing I might try to debug the broken transform is to maybe add own transform to dump intermediate results, something like:

```ts
plugins: [
  {
    name: "debug-transform",
    // enforce: "pre", 
    transform(code, id) {
      if (id.includes("ModalWrapper.tsx")) console.log({ id, code })
    }
  }
]
```

I'm not sure if Storybook is compatible, but you might also be able to debug using https://github.com/antfu-collective/vite-plugin-inspect
