### ISSUE TITLE
vite 库模式下 生产环境后，.module.less文件编译后异常无法使用样式

### ISSUE THREAD

**Issue by tzbcf** [vitejs/vite-plugin-react#358]
### Describe the bug

在dev环境下：import style from './index.module.less' ；     <p className={style.text}>{ text }</p>，使用正常；
在build后，index.module.less文件编译成index.module.less.js + index.module.css; 
编译的js中：import r from "./index.module.less.js"; React.createElement("p", { className: r.text }, t))；
样式使用异常。并被引入时，导致界面报错。
下面是我的vite.config.ts配置，希望有人能帮助我。谢谢！
export default defineConfig({
  build: {
    target: 'modules',
    outDir: "dist",
    minify: true,
    cssTarget: 'chrome61',
    cssCodeSplit: true,
    lib: {
      // 组件库源码的入口文件
      entry: path.resolve(__dirname, './package/index.ts'),
      formats:['es']
    },
    rollupOptions: {
      external: ['react', 'react-dom'],
      input: './package/index.ts',
      output: {
          format: "cjs",
          entryFileNames: '[name].js',
          chunkFileNames: '[name].js',
          assetFileNames: '[name].[ext]',
          //让打包目录和我们目录对应
          preserveModules: true,
          exports: "named",
          dir: path.resolve(__dirname, "./dist"),
          //配置打包根目录
          globals: {
            react: 'react',
            'react-dom': 'react-dom',
          },
        },
    },
  },
  css: {
    transformer: 'postcss',
    modules: {
      scopeBehaviour: 'local'
    },
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      }
    },
  },
  plugins: [
    react({
    jsxRuntime: 'classic'
    }),
    dts({
      entryRoot: "package",
      outDir: path.resolve(__dirname, "./dist"),
      exclude: ['./node_modules'],
      tsconfigPath: "./tsconfig.app.json",
    }),
  ],
})

### Reproduction

http://localhost:5173/

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 6.73 GB / 15.90 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1
```

### Used Package Manager

npm

### Logs

![image](https://github.com/user-attachments/assets/84429da2-af3b-4222-845a-91bb7518c569)
![image](https://github.com/user-attachments/assets/95088d21-5022-452c-9fa7-8296d4ae5cd7)
![image](https://github.com/user-attachments/assets/f6abc921-71af-439e-bab4-43960a5c5faa)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Please report issues in english using translation tools and with a reproduction
