### ISSUE TITLE
White screen when running on IOS12

### ISSUE THREAD

**Issue by MrQinYQ** [vitejs/vite-plugin-react#362]
### Describe the bug

error massage:
SyntaxError: Unexpected token '?'

builded file
![image](https://github.com/user-attachments/assets/b892ec48-efca-4593-8600-d60bedc241dd)

react sourcefile
![image](https://github.com/user-attachments/assets/34720a99-a188-4a00-b6ce-b9b01062872a)

vite config
```typescript
import { 
  defineConfig, 
} from 'vite'
import react from '@vitejs/plugin-react'


// https://vitejs.dev/config/
export default defineConfig({
  build: {
    sourcemap: true,
  },
  plugins: [
    react({
      babel: {
        browserslistConfigFile: true,
        browserslistEnv: 'production'
      }
    }), 
  ],
})

```

.browserslistrc
```
[production]
> 0.5%
last 2 versions
not dead
safari >= 11

[development]
last 1 chrome version
last 1 firefox version

```

### Reproduction

https://github.com/MrQinYQ/vite-test.git

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 80.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.asdf/installs/nodejs/20.2.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.2.0/bin/yarn
    npm: 9.6.6 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.33.6 - ~/.asdf/installs/nodejs/20.2.0/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.86
    Safari: 17.4.1
  npmPackages:
    @vitejs/plugin-legacy: ^5.4.2 => 5.4.2 
    @vitejs/plugin-react: ^4.3.1 => 4.3.1 
    @vitejs/plugin-react-swc: ^3.5.0 => 3.7.0 
    vite: ^5.4.2 => 5.4.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Babel doesn't run on node_modules in the React plugin, the correct way to support legacy browser is to use https://github.com/vitejs/vite/tree/main/packages/plugin-legacy

**Comment by MrQinYQ** [comment]
> Babel doesn't run on node_modules in the React plugin, the correct way to support legacy browser is to use https://github.com/vitejs/vite/tree/main/packages/plugin-legacy

If I know that I don't need to be compatible with browsers that don't support esmodule, but I need to be compatible with iOS 12, do I still need to introduce the legacy plugin? Is this reasonable?

**Comment by MrQinYQ** [comment]
I see, I should use: build.target

**Comment by ArnaudBarre** [comment]
Ah yeah if iOS 12 support almost everything except a few new syntax like `??` build.target should do it
