### ISSUE TITLE
Uncaught Error：@vitejs/plugin-react can't detect preamble. Something is wrong.

### ISSUE THREAD

**Issue by qiufeihong2018** [vitejs/vite-plugin-react#371]
### Describe the bug

1. Create a front-end project using `npm create vite@latest my-vite-react-ts-app -- --template react-ts`.
2. After startup, an error is reported: Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/issues/11.

### Reproduction

npm create vite@latest --template react-ts

### Steps to reproduce

2. Run the following command to create a new Vite project:

```sh
npm create vite@latest my-vite-react-ts-app -- --template react-ts
```

3. Enter the project directory:

```sh
cd my-vite-react-ts-app
```

4. Install dependencies:

```sh
yarn
```

5. Start the development server:

```sh
yarn dev
```

After startup, an error is reported:

![image](https://github.com/user-attachments/assets/89e063ca-2985-49b9-ba00-ce094be7dac6)

Later, it was found that the browser version is related.

There is an error with chrome 95.0.4638.69.

When switching to chrome version 112.0.5615.138 (official version) (64-bit), it can run normally.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 1.33 GB / 15.70 GB
  Binaries:
    Node: 18.20.4 - C:\Program Files\nodejs\node.EXE 
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD 
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD    
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1
    vite: ^5.4.1 => 5.4.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I guess you see the following error as well.

> TypeError: Cannot read property 'forEach' of undefined

This error happens when you are using an old react devtools extension: https://github.com/facebook/react/issues/25019

**Comment by ArnaudBarre** [comment]
Thanks for looking into it @sapphi-red!
We don't encourage looking such an old browser for dev anyway

**Comment by qiufeihong2018** [comment]
Thanks
