### ISSUE TITLE
Deno + Vite: TS starter working but not JS

### ISSUE THREAD

**Issue by mbrahimi02** [vitejs/vite-plugin-react#377]
### Describe the bug

I'm creating a deno project with site using `deno run -A npm:create-vite-extra` and all works fine if I select the TS project. If I select the JS project, I get the following despite the fact that types are installed and configured by default:

```
TypeError: createRoot is not a function. (In 'createRoot(document.getElementById("root"))', 'createRoot' is undefined)
```

### Reproduction

I can't add bc there's no way to select runtime

### Steps to reproduce

`deno run -A npm:create-vite-extra` with JavaScript project

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: Unknown
    Memory: 48.11 KB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Safari: 18.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
That's an oversight from @bluwy in https://github.com/bluwy/create-vite-extra/commit/fcaf8b185e803db6efbca12d2b605e0a20158609, createRoot should be imported from `react-dom` and StrictMode from `react`

**Comment by bluwy** [comment]
My bad. Will fix that in the next release
