### ISSUE TITLE
hmr update /app/routes/home.tsx (x75)

### ISSUE THREAD

**Issue by paulm17** [vitejs/vite-plugin-react#384]
### Describe the bug

Video: 
https://streamable.com/i857nl

Repo:
https://github.com/paulm17/rrv7

### Steps to reproduce

npm install
npm run dev

### System Info

```shell
Mac: 12.6
Node: v22
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I don't think react-router uses `@vitejs/plugin-react` from this repo. Please check with their issue https://github.com/remix-run/react-router/

**Comment by paulm17** [comment]
It happens with tanstack start too and sometimes with vinxi.  The main culprit is SSR with vite.  Anyway, I've decided to regress and just use tanstack router.  No ssr then and thus this issue doesn't exist.
