### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "react/jsx-dev-runtime" from "src/main.tsx". Does the file exist?

### ISSUE THREAD

**Issue by mrdulin** [vitejs/vite-plugin-react#391]
### Describe the bug

Try to use vite with react 16.10.0, got the error when start the dev server

### Reproduction

https://stackblitz.com/edit/vitejs-vite-q3yh8t?file=src%2Fmain.tsx

### Steps to reproduce

1. Remove the `package-lock.json`
2. `npm install && npm run dev`

### System Info

```shell
❯ npx envinfo --system --npmPackages '{vite,@vitejs/*}' --binaries --browsers
Need to install the following packages:
envinfo@7.14.0
 

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^4.3.4 => 4.3.4 
    vite: ^6.0.1 => 6.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`react({ jsxRuntime: 'classic' })` is needed for React 16 https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#jsxruntime
Then you need to manually have `import React from "react"` for jsx files https://stackblitz.com/edit/vitejs-vite-n8d2mc?file=tsconfig.app.json. You can use `compilerOptions.jsx: "react"` to ensure typescript help catching missing `React`.
