### ISSUE TITLE
Main.jsx 404 not found for github pages of repository

### ISSUE THREAD

**Issue by webdevamit** [vitejs/vite-plugin-react#54]
### Describe the bug

Hi team,
i found that while the vite build react app works fine on local but when i deployed this code to git repository and trying to setup git page for this repo, this fails and shows 404 for main.jsx file in repository 
this is the github repo - https://github.com/webdevamit/comment-box
and github page link - https://webdevamit.github.io/comment-box/
as per vite documentation i have added deploy.sh file as well

### Reproduction

https://webdevamit.github.io/comment-box/

### Steps to reproduce

just follow the git repository to see the changes

### System Info

```shell
npm package is used to install dependencies
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
You should build your app before deploying (`npm run build`)

More documentation here: https://vitejs.dev/guide/static-deploy.html#deploying-a-static-site
