### ISSUE TITLE
setting config options for Babel preset returns error

### ISSUE THREAD

**Issue by Idonoghue** [vitejs/vite-plugin-react#62]
### Describe the bug

I'm trying to pass a config object to `@babel/preset-react`. However an error is returned that the key is not recognized. I wonder if there is an issue is how this config object is passed to babel?
<img width="852" alt="Screen Shot 2022-12-16 at 11 42 34 AM" src="https://user-images.githubusercontent.com/7452455/208167152-85efefa0-b8c7-4ba9-bcb3-af723cb08a64.png">

### Reproduction

https://stackblitz.com/edit/vite-react-ts-vwcmyl?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 91.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.volta/tools/image/node/16.14.0/bin/node
    Yarn: 1.22.10 - ~/.volta/bin/yarn
    npm: 6.14.17 - ~/Documents/Projects/ADDI/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 91.0.1
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0 
    vite: ^4.0.1 => 4.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
The solution is at the end of the error ;)
You're missing a pair a square brackets

Also I don't know if this was simplified for reproduction (and then that's good), but probably you don't need this preset.
Runtime is automatic by default

**Comment by Idonoghue** [comment]
Just wow... I read that and everything and completely missed the extra brackets. So sorry to take your time on this 🤦

**Comment by Idonoghue** [comment]
For reference [the docs for @babel/preset-react](https://babeljs.io/docs/en/babel-preset-react#runtime) list `classic` as the default. If this option is not sent it fails to serve with `ReferenceError: React is not defined`

**Comment by ArnaudBarre** [comment]
What I mean is that you probably don't need to change the config at all, the default of the Vite React plugin is automatic runtime

**Comment by Idonoghue** [comment]
ahhh ok. So the preset is redundant, gotcha! We originally added this [when instrumenting our code for Cypress](https://docs.cypress.io/guides/tooling/code-coverage#Using-code-transpilation-pipeline) but it makes sense that setting our babel config through a react plugin would have the correct config by default. Thanks for the tip!
