### ISSUE TITLE
Failed to NextJS build project after upgrade to Vite 4.0 and @vite/plugin-react 3.0

### ISSUE THREAD

**Issue by vojtechmares** [vitejs/vite-plugin-react#64]
### Describe the bug

I can't run `pnpm run build` successfully. See Netlify job log https://app.netlify.com/sites/vojtechmares-website/deploys/639fa7cc04318b69d7824100

### Reproduction

https://github.com/vojtechmares/website branch vite-4.x

### Steps to reproduce

1. clone the repository
2. checkout to branch `vite-4.x` (`git switch vite-4.x`)
3. install dependencies via `pnpm` (`pnpm i --frozen-lockfile`)
4. Build the site `pnpm run build`

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1010.34 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox Developer Edition: 101.0
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0
    vite: ^4.0.2 => 4.0.2

*manually added, pnpm: 7.18.2
```

### Used Package Manager

pnpm

### Logs

See: https://app.netlify.com/sites/vojtechmares-website/deploys/639fa7cc04318b69d7824100

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
> 8:53:18 AM: ./vitest.config.ts:10:5
8:53:18 AM: Type error: Type 'PluginOption[]' is not assignable to type 'PluginOption'.
8:53:18 AM:   Type 'import("/opt/build/repo/node_modules/.pnpm/vite@4.0.2_@types+node@18.11.12/node_modules/vite/dist/node/index").PluginOption[]' is not assignable to type 'import("/opt/build/repo/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.12/node_modules/vite/dist/node/index").PluginOption[]'.

This error is not coming from Vite. This is an TypeScript error due to multiple Vite installed.
See https://github.com/vitest-dev/vitest/issues/2486

**Comment by vojtechmares** [comment]
My bad.

There was a dependency update triggered via renovate, unfortunately it turned into "waterfall of dependency upgrades".

I managed to locate the source of vite@3.2.5 and get rid of it, fixining this issue.

I had to upgrade a few other things as well as @types/node.
