### ISSUE TITLE
Cannot use className on any custom HTML element. 

### ISSUE THREAD

**Issue by Ministerra** [vitejs/vite-plugin-react#66]
### Describe the bug

Hi, I´m currently rewriting my JS app into React with Vite. Im using a lot of custom HTML elements just because they make everything more organized (for example <userinput-wrapper> or <portraits-container> etc. However for some reason, I can´t use them with Vite, because "className" doesnt work on them. The CSS is not applied at all. I can use "class" (which works), but then I get huge amounts of warnings inside the dev tool, because class is not valid DOM property. How can I solve this please?

### Reproduction

no need, just try to use className on any custom HTML element

### Steps to reproduce

const TestingComponent = () => {
    const wrapper = 'flexCol marAuto aliCen wr30';
    const input = 'w100';

    return (
        <div>
            <div className={wrapper}>
                <label htmlFor="username">Username</label>
                <input className={input} type="text" id="username" />
            </div>

            <div class={wrapper}>
                <label htmlFor="age">Age</label>
                <input className={input} type="number" id="age" />
            </div>
        </div>
    );
};

export default TestingComponent;

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 2.03 GB / 7.86 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0
    vite: ^4.0.0 => 4.0.2
```

### Used Package Manager

npm

### Logs

const TestingComponent = () => {
    const wrapper = 'flexCol marAuto aliCen wr30';
    const input = 'w100';

    return (
        <div>
            <div className={wrapper}>
                <label htmlFor="username">Username</label>
                <input className={input} type="text" id="username" />
            </div>

            <div class={wrapper}>
                <label htmlFor="age">Age</label>
                <input className={input} type="number" id="age" />
            </div>
        </div>
    );
};

export default TestingComponent;

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
This is how React works. You need to use `class` instead of `className` for custom elements.
https://reactjs.org/docs/web-components.html#using-web-components-in-react:~:text=One%20common%20confusion%20is%20that%20Web%20Components%20use%20%E2%80%9Cclass%E2%80%9D%20instead%20of%20%E2%80%9CclassName%E2%80%9D.

**Comment by gybeasmz** [comment]
Hello Sapphi, thank you for the answer! I still wonder, how I can get rid of that "Did you mean className" warning in DEV tools? Because getting it for all custom HTML tags is gonna be pain in the ass. Not acceptable.

**Comment by sapphi-red** [comment]
I don't know. I assume that warning is coming from React and not from Vite or plugin-react. (I haven't checked as there wasn't a reproduction on this issue though.)
I think you could ask that question on the react related forums.
