### ISSUE TITLE
JSX in TypeScript namespace causes error

### ISSUE THREAD

**Issue by AmazingShine** [vitejs/vite-plugin-react#7]
### Describe the bug

Jsx in namespace is not supported, similar to this bug: [#22413](https://github.com/facebook/react/issues/22413)

### Reproduction

pnpm create vite demo --template react-ts

### Steps to reproduce

https://stackblitz.com/edit/vitejs-vite-o1zmeh?file=src%2FApp.tsx&terminal=dev

Create a official demo: `pnpm create vite demo --template react-ts`.
And then write the following code:
```ts
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

namespace AAA {
    export const Hello = () => <div>Hello</div>
}

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
        <AAA.Hello></AAA.Hello>
    </div>
  )
}

export default App
```

### System Info

```shell
System:
    OS: Linux 5.19 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
    Memory: 20.67 GB / 31.17 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
```

### Used Package Manager

pnpm

### Logs

This error occured:
```
Internal server error: Transform failed with 1 error:
.../demo/src/App.tsx:14:5: ERROR: Cannot use "this" here:
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
For automatic runtime, Vite uses babel to transform JSX and esbuild to transform TS.

```ts
// input
namespace AAA {
  export const Hello = () => <div>Hello</div>
}

// output from babel
namespace AAA {
  export const Hello = () => /*#__PURE__*/_jsxDEV("div", {
    children: "Hello"
  }, void 0, false, {
    fileName: _jsxFileName,
    lineNumber: 5,
    columnNumber: 30
  }, this);
  _c = Hello;
}
```
This output uses `this` in `namespace` and esbuild throws an error for that. Vite needs to inject a custom babel plugin to babel to transform this `this` to `void 0`. vitejs/vite#9590 might fix this indirectly.

---

For classic runtime, Vite uses babel to add debug information and esbuild to transform JSX+TS.
```ts
// input
namespace AAA {
  export const Hello = () => <div>Hello</div>
}

// output from babel
namespace AAA {
  export const Hello = () => <div __self={this} __source={{
    fileName: _jsxFileName,
    lineNumber: 5,
    columnNumber: 30
  }}>Hello</div>;
  _c = Hello;
}
```
We need to use a similar babel plugin for this case too.

**Comment by sapphi-red** [comment]
Closing as I confirmed plugin-react 3.0.0 works with this. plugin-react now uses esbuild to transform JSX and I think that fixed this.
