### ISSUE TITLE
Support custom JSX package

### ISSUE THREAD

**Issue by leonardoraele** [vitejs/vite-plugin-react#78]
### Description

Right now, the plugin always transforms jsx expressions into `React.createElement` calls in classic mode, and always imports `jsx` from `react/jsx-runtime` in automatic runtime. This makes it impossible to use custom jsx packages.

### Suggested solution

In classic runtime, the `this` object to which `createElement()` calls are made should be configurable; and in automatic runtime, the package from which `jsx` is imported should be configurable.

### Example: (automatic runtime)
```js
// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react({
    jsxPackage: 'my-jsx-package', // New proposed option
  })],
})
```

```js
// Input (test.jsx)
export default Test() {
  return <div class="header">Hello World</div>
}
```

```js
// Output
import { jsx as _jsx } from 'my-jsx-package/jsx-runtime' // imported from custom package instead of 'react'

export default Test() {
  return _jsx('div', { class: 'header' }, 'Hello World')
}
```

### Example (classic runtime)
```js
// vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react({
    jsxRuntime: 'classic',
    jsxPragma: 'h', // New proposed option
    jsxPragmaFragment: 'h.fragment', // New proposed option
  })],
})
```

```js
// Input (test.jsx)
import { h } from 'custom-jsx' // Instead of `import React from 'react'`

export default Test({ message }) {
  return (
    <>
      <div>Hello World</div>
      <div>{ message }</div>
    </>
  )
}
```

```js
// Output
import { h } from 'custom-jsx'

export default Test({ message }) {
  return h(h.fragment, null, [
    h('div', null, 'Hello World'),
    h('div', null, message)
  ])
}
```

### Alternative

The current alternative is to use classic runtime and manipulate the imports in a way that mimics react API.

Example:
```js
// custom-jsx-wrapper.js
import { h } from 'custom-jsx'

export default { createElement: h, Fragment: h.fragment }
```

```js
// test.jsx
import React from './custom-jsx-wrapper.js'

export default Test() {
  return <div>Hello World</div>
}
```

### Additional context

This feature is supported by `babel-plugin-transform-react-jsx`, through `importSource`, `pragma`, and `pragmaFrag` options.

Doc:
https://babeljs.io/docs/en/babel-plugin-transform-react-jsx.html#importsource

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ArnaudBarre** [comment]
You can use `jsxImportSource` for automatic runtime.
jsx tranform is done via esbuild now, so for classic runtime you can directly configure esbuild: https://vitejs.dev/config/shared-options.html#esbuild

**Comment by leonardoraele** [comment]
Thanks, @ArnaudBarre.  Great to hear it's already supported. But I'm also a bit frustrated that it's not included in the [docs](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md). Should I create a PR to update it?

**Comment by ArnaudBarre** [comment]
Oh yeah true. Fell free to open a PR! I will do it this week otherwise
