### ISSUE TITLE
Fast Refresh not working with automatic runtime and file extension without "x"

### ISSUE THREAD

**Issue by cknitt** [vitejs/vite-plugin-react#83]
### Describe the bug

Currently, fast refresh is working for a file only if either

- the file extension ends with an "x" (e.g. "jsx", "tsx") *or*
- the code in the file imports `React` in some way

Now when using a compile-to-JS language like [ReScript](https://rescript-lang.org/) **with the new JSX runtime enabled**, one can get `.js` or `.mjs` files with imports from "react/jsx-runtime" or "react/jsx-dev-runtime", but no `React` import, and fast refresh will not work for these files.

### Reproduction

https://github.com/cknitt/vite-plugin-react-fast-refresh-issue

### Steps to reproduce

1. Install dependencies and start vite:
```sh
npm i
npm run dev
```
2. Increment counter
3. Change the text in `TestComponent.bs.js` (alternatively change it in TestComponent.res and run `npm run res:build` to recompile). Observe that the counter value is reset to 0.

### Workaround

1. Run `npx patch-package` to apply the patch from `patches/@vitejs+plugin-react+3.0.1.patch`.
2. Restart vite and repeat the above test steps.
3. Observe that TestComponent now refreshs correctly and the counter value remains unchanged.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 893.44 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/Caches/fnm_multishells/60384_1673351682301/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/Library/Caches/fnm_multishells/60384_1673351682301/bin/npm
    Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 108.1.46.153
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.0.1
    vite: ^4.0.4 => 4.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Thanks for the repro. I will take this into account for the API of the v4

**Comment by cknitt** [comment]
@ArnaudBarre Thanks! 🙂

I think that at https://github.com/vitejs/vite-plugin-react/blob/d758a2a44b0a2cb3c206fa61166cda9d5cf58221/packages/plugin-react/src/index.ts#L113 instead of checking for "React" in e.g. `import * as React from 'react';`, we should check for the package name (one of "react", "react/jsx-runtime", or "react/jsx-dev-runtime"). Right?

**Comment by ArnaudBarre** [comment]
This would work for jsx because this is the only use for this subpath, but not for "react", because this can be a file with just React hooks. This condition needs to be adapted based on the runtime type, I will do that

**Comment by netoya** [comment]
I think with can use 
```js
/^[A-Z]([^\.])+\.[t|j]sx?/.test(filepath.split("/").pop())
```
because all components files start with UpperCase
