### ISSUE TITLE
Failed to fetch dynamically imported module when importing StencilJS React Components

### ISSUE THREAD

**Issue by crrobinson14** [vitejs/vite-plugin-react#89]
### Describe the bug

When importing a Web Component built in StencilJS using their React export option, Vite (Rollup) reports `Failed to fetch dynamically imported module` and terminates. It looks like other plugins like https://github.com/vitejs/vite-plugin-vue introduced a `compilerOptions` setting which allows syntax like

```
compilerOptions: {
    isCustomElement: (tag) => tag.startsWith('mycomponent-')
}
```

but vite-plugin-react does not. Is there another way to resolve this, or is this even the right answer?

The repro steps below work properly in Webpack so my assumption is some flag must be passed to RollUp to tell it what's going on. So while the issue is probably in RollUp, I'm reporting it here because I believe something in this plugin needs to be configured/passed through to it as is done with @vite/plugin-vue...

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ity84s?file=src/App.jsx

### Steps to reproduce

1. Install any Web Component library with React bindings. In the repro above, @verdocs/web-sdk-react is built using StencilJS and their React target plugin.
2. Add any component to the app. In the repro above, `VerdocsSign` is shown, but any component will do. Bogus parameters may be used.
3. Observe error in console when app renders:

```@verdocs_web-sdk-react.js?v=8b435f6a:1538          GET https://vitejsviteity84s-q50n--5173.local-credentialless.webcontainer.io/node_modules/.vite/deps/verdocs-sign.entry.js?import net::ERR_ABORTED 504 (Gateway Timeout)
...
11:31:32.195 @verdocs_web-sdk-react.js?v=8b435f6a:1528 TypeError: Failed to fetch dynamically imported module: https://vitejsviteity84s-q50n--5173.local-credentialless.webcontainer.io/node_modules/.vite/deps/verdocs-sign.entry.js?import undefined
...
11:31:32.196 @verdocs_web-sdk-react.js?v=8b435f6a:1328 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isProxied')
...
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 65.39 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 103.0.2
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
I looked at the issue. The lib is explicitly using `/* vite-ignore */` in dynamic import and the path created doesn't exist.

Found the source code here: https://github.com/ionic-team/stencil/blob/main/src/client/client-load-module.ts#L32

I don't have a solution for you right now, this would take a lot of times to understand how the lib expect this to works and how Vite handles dynamic import inside dependencies.

Maybe the solution could be to help Vite pre-bundling some dependencies that were not scanned via optimizeDeps.include

**Comment by PottierAlexis** [comment]
Hello,

I just had the exacte same issue in my project and could resolve it by adding the [experimentalImportInjection](https://stenciljs.com/docs/config-extras#experimentalimportinjection) flag in my stencil library.

Thanks to the line shared by @ArnaudBarre, I was able to find a commit message referencing this problem, and it solution.
https://github.com/ionic-team/stencil/pull/2959#

Hope it will work in your case.

**Comment by ArnaudBarre** [comment]
Thanks for your investigation @PottierAlexis 

I'm closing the issue for now. I don't see anything the plugin is doing wrong and they seems to know about the issue.

Feel free to comment if you think the plugin could do something to support this without depending on internal of another framework.
