### ISSUE TITLE
React-Plugin does not respect the jsxImportSource from TSConfig 

### ISSUE THREAD

**Issue by seivan** [vitejs/vite-plugin-react#9]
### Description

A user shouldn't have to define `jsxImportSource` twice, if it's in a `TSConfig` then it's already defined. 
ESBuild (and hopefully Vite) already respects that as far as I know for: 
[jsxFactory](https://www.typescriptlang.org/tsconfig#jsxFactory)
[jsxFragmentFactory](https://www.typescriptlang.org/tsconfig#jsxFragmentFactory)

I think the plugin should do that for jsxImportSource as well. 

### Suggested solution

Read `TSConfig.compilerOptions.jsxImportSource ?? options?.jsxImportSource ??  "react"`

### Alternative

Building a  [shim](https://esbuild.github.io/content-types/#auto-import-for-jsx) for the auto-import and let ESBuild the whole thing instead of using the plugin. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by seivan** [comment]
Notes: 

- [ ] TSConfing `"jsx": "react"` is opt out of automatic runtime. 
- [ ] TSConfig defined `"jsxImportSource": "react"` is default to current settings. 
- [ ] Anything else, read pass on as is. 


Did a go at it. 

```ts
const jsxImportSrc = tsBuildConfig.compilerOptions.jsxImportSource
const jsxOption = tsBuildConfig.compilerOptions.jsx === "react"
  ? {}
  : jsxImportSrc === "react"
    ? {}
    : { jsxRuntime: "automatic" as const, jsxImportSrc, }


ReactPlugin({ ...jsxOption, })
```


Worked perfectly with others, like `@emotion/react`

```ts
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
```
and
```ts
    "jsx": "react-jsx",
    "jsxImportSource": "react",
```

**Comment by bluwy** [comment]
Does esbuild support `jsxImportSource`? According to https://esbuild.github.io/content-types/#tsconfig-json only a few fields are supported which Vite [passes](https://github.com/vitejs/vite/blob/ce790c4080b6592ed60edfcf90a9ec344d575fa1/packages/vite/src/node/plugins/esbuild.ts#L93-L98). Maybe this is related to plugin-react and it's babel transform, but regardless it would be great if you can submit the PR so it's easier to view the proposed changes.

**Comment by seivan** [comment]
All the heavy lifting is already done by the React plugin, this is purely a convenience feature. Making sure that we don't repeat configs and keep one single source of truth.

**Comment by alex-kinokon** [comment]
Yes, esbuild [does support](https://github.com/evanw/esbuild/pull/2349) `jsxImportSource`.

**Comment by ArnaudBarre** [comment]
Now that jsx transformation is done by esbuild and that the esbuild plugin correctly read this options, it _should_ be as easy as removing this line https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts#L152 for TS projects.

This should also enable multiple runtime per app that someone asked in the discussions.
 
But I don't know how to handle that for JS project (or more complicated, mixed projects)

**Comment by ArnaudBarre** [comment]
Hi!
Just tested with the latest version of Vite and the plugin and it it's already working in fact (with one TS config that specify `jsxImportSource` and no options for the react plugin).
If you have a more complex usecase not supported please share a repro
