### ISSUE TITLE
Bad version of React build used in production build

### ISSUE THREAD

**Issue by bOOm-X** [vitejs/vite-plugin-react#90]
### Describe the bug

When building in production mode, the react build file used is: `react.development.js`
It should be `react.production.min.js`.
To bypass this issue I need to add:
```
    define: {
      'process.env.NODE_ENV': '"production"',
    }
```
in my vite config (in `vite.config.ts`)
For me, this should be handled automatically by this plugin. What do you think ?
It is quite easy to handle it.
the following option should be added in `packages/plugin-react/src/index.ts` (line 150 & 160)
`define: {'process.env.NODE_ENV': `"${mode}"`}`
I can do a PR if you want !

Thanks !

### Reproduction

any vite + @vitejs/plugin-react build

### System Info

```shell
vite: v4.0.4
@vitejs/plugin-react: v3.0.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
Hi

I do not repro this with a fresh template (`yarn create vite`) + `TypeScript` option + `yarn && yarn build`

You probably have more things in you config that mess up with the environment variables.
