### ISSUE TITLE
Not able to get a dev build of react

### ISSUE THREAD

**Issue by samdoeswork** [vitejs/vite-plugin-react#91]
### Describe the bug

I am running vite build --mode development , and I am getting the production build of React with minified errors.

I need to get real errors because of this significant long-lived issue: https://github.com/vitejs/vite/issues/2139

Being able to use the dev build of react would give me some way of trying to progress this, open helpful issues in third-party libraries, tec.

I've tried build: { minify: false, sourcemap: "inline" } in the main vite config along with mode: "development".

I still get an error message like this:

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

So I know that the long-lived issue referenced above is the cause of the actual error. This issue is that I can't get to the "non minified dev environment".

### Reproduction

https://stackblitz.com/edit/vitejs-vite-x4q1rv?file=vite.config.ts

### Steps to reproduce

npx vite build --mode development --minify false --sourcemap true

React is using the minified production build which removes errors.

### System Info

```shell
Windows & chrome
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArnaudBarre** [comment]
React code source is using `process.env.NODE_ENV === 'production'` check.

To build the app with a development version you can either do `NODE_ENV='development' npm run build` or use https://vitejs.dev/config/#conditional-config + https://vitejs.dev/config/shared-options.html#define to automatically set the node env to dev when mode is dev.

Note that this can have a lot of other side effects on the build output, a lot of the ecosystem is using this check.
